import { seoulLines } from '@/constants/theme';
import type { Course, Lesson, Unit } from '@/types/content';

export const COURSES: Course[] = [
  {
    id: 'course-starter',
    title: 'Korean Starter',
    description: 'Read Hangul and say your first real Korean sentences.',
    level: 1,
    orderIndex: 1,
    isPremium: false,
    emoji: '🌱',
    // Seoul Metro line colours: the city's own wayfinding palette.
    accent: seoulLines.line2,
  },
  {
    id: 'course-everyday',
    title: 'Everyday Korean',
    description: 'The Korean you actually use in a normal Seoul day.',
    level: 2,
    orderIndex: 2,
    isPremium: false,
    emoji: '☕',
    accent: seoulLines.line3,
  },
  {
    id: 'course-conversation',
    title: 'Korean Conversation',
    description: 'Keep a conversation going with friends and coworkers.',
    level: 3,
    orderIndex: 3,
    isPremium: true,
    emoji: '💬',
    accent: seoulLines.line8,
  },
  {
    id: 'course-living',
    title: 'Living in Korea',
    description: 'Banks, hospitals, delivery apps and apartment life.',
    level: 3,
    orderIndex: 4,
    isPremium: true,
    emoji: '🏙️',
    accent: seoulLines.line5,
  },
  {
    id: 'course-travel',
    title: 'Korean Travel',
    description: 'Airports, taxis, hotels and ordering like a local.',
    level: 2,
    orderIndex: 5,
    isPremium: true,
    emoji: '✈️',
    accent: seoulLines.line4,
  },
  {
    id: 'course-work',
    title: 'Korean for Work',
    description: 'Emails, meetings and 존댓말 that sounds professional.',
    level: 4,
    orderIndex: 6,
    isPremium: true,
    emoji: '💼',
    accent: seoulLines.line1,
  },
];

export const UNITS: Unit[] = [
  {
    id: 'unit-starter-1',
    courseId: 'course-starter',
    title: 'Hello Korea',
    description: 'Greetings, thank you, and introducing yourself.',
    orderIndex: 1,
  },
  {
    id: 'unit-starter-2',
    courseId: 'course-starter',
    title: 'Cafe Korean',
    description: 'Order coffee and pay like you live here.',
    orderIndex: 2,
  },
  {
    id: 'unit-starter-3',
    courseId: 'course-starter',
    title: 'Hangul Basics',
    description: 'Read 한글 letter by letter.',
    orderIndex: 3,
  },
  {
    id: 'unit-starter-4',
    courseId: 'course-starter',
    title: 'Numbers',
    description: 'Count, tell prices and give your phone number.',
    orderIndex: 4,
  },
  {
    id: 'unit-everyday-1',
    courseId: 'course-everyday',
    title: 'Food & Delivery',
    description: 'Restaurants, 배달 apps and convenience stores.',
    orderIndex: 1,
  },
  {
    id: 'unit-everyday-2',
    courseId: 'course-everyday',
    title: 'Getting Around',
    description: 'Subway, buses and taxis in Seoul.',
    orderIndex: 2,
  },
  {
    id: 'unit-everyday-3',
    courseId: 'course-everyday',
    title: 'Shopping',
    description: 'Sizes, prices and asking for help.',
    orderIndex: 3,
  },
  {
    id: 'unit-conversation-1',
    courseId: 'course-conversation',
    title: 'Making Friends',
    description: 'Small talk that does not feel like a textbook.',
    orderIndex: 1,
  },
  {
    id: 'unit-living-1',
    courseId: 'course-living',
    title: 'Daily Errands',
    description: 'Banks, post offices and package pickup.',
    orderIndex: 1,
  },
  {
    id: 'unit-travel-1',
    courseId: 'course-travel',
    title: 'Arrival',
    description: 'Airport, transport cards and checking in.',
    orderIndex: 1,
  },
  {
    id: 'unit-work-1',
    courseId: 'course-work',
    title: 'Office Korean',
    description: 'Greeting colleagues and joining a meeting.',
    orderIndex: 1,
  },
  {
    id: 'unit-conversation-2',
    courseId: 'course-conversation',
    title: 'Opinions & Feelings',
    description: 'Say what you think without sounding blunt.',
    orderIndex: 2,
  },
  {
    id: 'unit-conversation-3',
    courseId: 'course-conversation',
    title: 'Making Plans',
    description: 'Invite, reschedule and politely decline.',
    orderIndex: 3,
  },
  {
    id: 'unit-living-2',
    courseId: 'course-living',
    title: 'Health & Emergencies',
    description: 'Pharmacies, clinics and asking for help.',
    orderIndex: 2,
  },
  {
    id: 'unit-living-3',
    courseId: 'course-living',
    title: 'Home & Bills',
    description: 'Landlords, wifi, and the monthly 관리비.',
    orderIndex: 3,
  },
  {
    id: 'unit-travel-2',
    courseId: 'course-travel',
    title: 'Hotels & Stays',
    description: 'Check in, ask for late checkout, report a problem.',
    orderIndex: 2,
  },
  {
    id: 'unit-travel-3',
    courseId: 'course-travel',
    title: 'Sightseeing',
    description: 'Tickets, photos and asking locals for tips.',
    orderIndex: 3,
  },
  {
    id: 'unit-work-2',
    courseId: 'course-work',
    title: 'Email & Messages',
    description: 'Written Korean that reads professional.',
    orderIndex: 2,
  },
];

export const LESSONS: Lesson[] = [
  {
    id: 'lesson-greetings-hello',
    unitId: 'unit-starter-1',
    title: 'Hello & Goodbye',
    description: 'The two phrases you will use every single day.',
    lessonType: 'conversation',
    estimatedMinutes: 5,
    orderIndex: 1,
    isPremium: false,
  },
  {
    id: 'lesson-greetings-yesno',
    unitId: 'unit-starter-1',
    title: 'Yes & No',
    description: 'Agree, disagree and sound natural doing it.',
    lessonType: 'vocabulary',
    estimatedMinutes: 5,
    orderIndex: 2,
    isPremium: false,
  },
  {
    id: 'lesson-greetings-thanks',
    unitId: 'unit-starter-1',
    title: 'Thank You',
    description: 'Say thanks and reply when someone thanks you.',
    lessonType: 'conversation',
    estimatedMinutes: 5,
    orderIndex: 3,
    isPremium: false,
  },
  {
    id: 'lesson-greetings-intro',
    unitId: 'unit-starter-1',
    title: 'Introducing Yourself',
    description: 'Name, country and a friendly first impression.',
    lessonType: 'conversation',
    estimatedMinutes: 7,
    orderIndex: 4,
    isPremium: false,
  },
  {
    id: 'lesson-cafe-coffee',
    unitId: 'unit-starter-2',
    title: 'Ordering Coffee',
    description: 'Order an americano without switching to English.',
    lessonType: 'conversation',
    estimatedMinutes: 5,
    orderIndex: 1,
    isPremium: false,
  },
  {
    id: 'lesson-cafe-water',
    unitId: 'unit-starter-2',
    title: 'Asking for Water',
    description: 'Ask for water, napkins and a to-go cup.',
    lessonType: 'vocabulary',
    estimatedMinutes: 5,
    orderIndex: 2,
    isPremium: false,
  },
  {
    id: 'lesson-cafe-paying',
    unitId: 'unit-starter-2',
    title: 'Paying',
    description: 'Card, cash and points — the whole counter script.',
    lessonType: 'conversation',
    estimatedMinutes: 6,
    orderIndex: 3,
    isPremium: false,
  },
  {
    id: 'lesson-hangul-consonants',
    unitId: 'unit-starter-3',
    title: 'Hangul Consonants',
    description: 'The 14 basic consonants and how they sound.',
    lessonType: 'hangul',
    estimatedMinutes: 8,
    orderIndex: 1,
    isPremium: false,
  },
  {
    id: 'lesson-hangul-vowels',
    unitId: 'unit-starter-3',
    title: 'Hangul Vowels',
    description: 'Ten vowels built from three simple strokes.',
    lessonType: 'hangul',
    estimatedMinutes: 8,
    orderIndex: 2,
    isPremium: false,
  },
  {
    id: 'lesson-numbers-sino',
    unitId: 'unit-starter-4',
    title: 'Numbers for Money',
    description: 'Sino-Korean numbers for prices and dates.',
    lessonType: 'vocabulary',
    estimatedMinutes: 6,
    orderIndex: 1,
    isPremium: false,
  },
  {
    id: 'lesson-numbers-native',
    unitId: 'unit-starter-4',
    title: 'Counting Things',
    description: 'Native Korean numbers for cups, people and hours.',
    lessonType: 'vocabulary',
    estimatedMinutes: 6,
    orderIndex: 2,
    isPremium: false,
  },
  {
    id: 'lesson-food-restaurant',
    unitId: 'unit-everyday-1',
    title: 'At a Restaurant',
    description: 'Order for the table and ask for the check.',
    lessonType: 'conversation',
    estimatedMinutes: 7,
    orderIndex: 1,
    isPremium: false,
  },
  {
    id: 'lesson-food-convenience',
    unitId: 'unit-everyday-1',
    title: 'Convenience Store',
    description: 'The 편의점 phrases nobody teaches you.',
    lessonType: 'conversation',
    estimatedMinutes: 6,
    orderIndex: 2,
    isPremium: false,
  },
  {
    id: 'lesson-transport-subway',
    unitId: 'unit-everyday-2',
    title: 'Taking the Subway',
    description: 'Transfers, exits and asking which line.',
    lessonType: 'conversation',
    estimatedMinutes: 7,
    orderIndex: 1,
    isPremium: false,
  },
  {
    id: 'lesson-transport-taxi',
    unitId: 'unit-everyday-2',
    title: 'Taking a Taxi',
    description: 'Give an address and ask to stop here.',
    lessonType: 'conversation',
    estimatedMinutes: 6,
    orderIndex: 2,
    isPremium: true,
  },
  {
    id: 'lesson-shopping-sizes',
    unitId: 'unit-everyday-3',
    title: 'Sizes & Colors',
    description: 'Try it on and ask for another size.',
    lessonType: 'vocabulary',
    estimatedMinutes: 6,
    orderIndex: 1,
    isPremium: true,
  },
  {
    id: 'lesson-conversation-smalltalk',
    unitId: 'unit-conversation-1',
    title: 'Small Talk',
    description: 'Weather, weekends and what you did yesterday.',
    lessonType: 'conversation',
    estimatedMinutes: 8,
    orderIndex: 1,
    isPremium: true,
  },
  {
    id: 'lesson-living-delivery',
    unitId: 'unit-living-1',
    title: 'Package Delivery',
    description: 'Talk to the 택배 driver and the front desk.',
    lessonType: 'conversation',
    estimatedMinutes: 7,
    orderIndex: 1,
    isPremium: true,
  },
  {
    id: 'lesson-travel-airport',
    unitId: 'unit-travel-1',
    title: 'At the Airport',
    description: 'Immigration, T-money and the airport bus.',
    lessonType: 'conversation',
    estimatedMinutes: 7,
    orderIndex: 1,
    isPremium: true,
  },
  {
    id: 'lesson-work-greetings',
    unitId: 'unit-work-1',
    title: 'Office Greetings',
    description: '수고하셨습니다 and when to actually use it.',
    lessonType: 'culture',
    estimatedMinutes: 6,
    orderIndex: 1,
    isPremium: true,
  },
  {
    id: 'lesson-conversation-opinions',
    unitId: 'unit-conversation-2',
    title: 'Giving an Opinion',
    description: 'Agree, disagree and soften it the Korean way.',
    lessonType: 'conversation',
    estimatedMinutes: 8,
    orderIndex: 1,
    isPremium: true,
  },
  {
    id: 'lesson-conversation-feelings',
    unitId: 'unit-conversation-2',
    title: 'Talking About Feelings',
    description: 'Tired, excited, stressed — say it naturally.',
    lessonType: 'vocabulary',
    estimatedMinutes: 7,
    orderIndex: 2,
    isPremium: true,
  },
  {
    id: 'lesson-conversation-plans',
    unitId: 'unit-conversation-3',
    title: 'Making Plans',
    description: 'Suggest a time and place without over-explaining.',
    lessonType: 'conversation',
    estimatedMinutes: 8,
    orderIndex: 1,
    isPremium: true,
  },
  {
    id: 'lesson-conversation-declining',
    unitId: 'unit-conversation-3',
    title: 'Saying No Politely',
    description: 'Decline an invitation without any awkwardness.',
    lessonType: 'culture',
    estimatedMinutes: 7,
    orderIndex: 2,
    isPremium: true,
  },
  {
    id: 'lesson-living-pharmacy',
    unitId: 'unit-living-2',
    title: 'At the Pharmacy',
    description: 'Describe a symptom and get the right medicine.',
    lessonType: 'conversation',
    estimatedMinutes: 8,
    orderIndex: 1,
    isPremium: true,
  },
  {
    id: 'lesson-living-emergency',
    unitId: 'unit-living-2',
    title: 'Getting Help Fast',
    description: 'The few sentences you hope never to need.',
    lessonType: 'vocabulary',
    estimatedMinutes: 6,
    orderIndex: 2,
    isPremium: true,
  },
  {
    id: 'lesson-living-apartment',
    unitId: 'unit-living-3',
    title: 'Apartment Problems',
    description: 'Report a leak, no hot water or a broken lock.',
    lessonType: 'conversation',
    estimatedMinutes: 8,
    orderIndex: 1,
    isPremium: true,
  },
  {
    id: 'lesson-travel-hotel',
    unitId: 'unit-travel-2',
    title: 'Checking In',
    description: 'Reservations, luggage and late checkout.',
    lessonType: 'conversation',
    estimatedMinutes: 7,
    orderIndex: 1,
    isPremium: true,
  },
  {
    id: 'lesson-travel-sightseeing',
    unitId: 'unit-travel-3',
    title: 'Tickets & Photos',
    description: 'Buy entry, ask for a photo, find the good spot.',
    lessonType: 'conversation',
    estimatedMinutes: 7,
    orderIndex: 1,
    isPremium: true,
  },
  {
    id: 'lesson-work-email',
    unitId: 'unit-work-2',
    title: 'Writing a Work Message',
    description: 'Openers, requests and closings that read right.',
    lessonType: 'grammar',
    estimatedMinutes: 8,
    orderIndex: 1,
    isPremium: true,
  },
];
