import { seoulLines } from '@/constants/theme';
import type { Course, Lesson, Unit } from '@/types/content';

export const COURSES: Course[] = [
  {
    id: 'course-starter',
    title: 'Korean Starter',
    description: 'Read Hangul and say your first real Korean sentences.',
    level: 1,
    orderIndex: 1,
    isPremium: false,
    emoji: '🌱',
    // Seoul Metro line colours: the city's own wayfinding palette.
    accent: seoulLines.line2,
  },
  {
    id: 'course-everyday',
    title: 'Everyday Korean',
    description: 'The Korean you actually use in a normal Seoul day.',
    level: 2,
    orderIndex: 2,
    isPremium: false,
    emoji: '☕',
    accent: seoulLines.line3,
  },
  {
    id: 'course-conversation',
    title: 'Korean Conversation',
    description: 'Keep a conversation going with friends and coworkers.',
    level: 3,
    orderIndex: 3,
    isPremium: true,
    emoji: '💬',
    accent: seoulLines.line8,
  },
  {
    id: 'course-living',
    title: 'Living in Korea',
    description: 'Banks, hospitals, delivery apps and apartment life.',
    level: 3,
    orderIndex: 4,
    isPremium: true,
    emoji: '🏙️',
    accent: seoulLines.line5,
  },
  {
    id: 'course-travel',
    title: 'Korean Travel',
    description: 'Airports, taxis, hotels and ordering like a local.',
    level: 2,
    orderIndex: 5,
    isPremium: true,
    emoji: '✈️',
    accent: seoulLines.line4,
  },
  {
    id: 'course-work',
    title: 'Korean for Work',
    description: 'Emails, meetings and 존댓말 that sounds professional.',
    level: 4,
    orderIndex: 6,
    isPremium: true,
    emoji: '💼',
    accent: seoulLines.line1,
  },
];

export const UNITS: Unit[] = [
  {
    id: 'unit-starter-1',
    courseId: 'course-starter',
    title: 'Hello Korea',
    description: 'Greetings, thank you, and introducing yourself.',
    orderIndex: 1,
  },
  {
    id: 'unit-starter-2',
    courseId: 'course-starter',
    title: 'Cafe Korean',
    description: 'Order coffee and pay like you live here.',
    orderIndex: 2,
  },
  {
    id: 'unit-starter-3',
    courseId: 'course-starter',
    title: 'Hangul Basics',
    description: 'Read 한글 letter by letter.',
    orderIndex: 3,
  },
  {
    id: 'unit-starter-4',
    courseId: 'course-starter',
    title: 'Numbers',
    description: 'Count, tell prices and give your phone number.',
    orderIndex: 4,
  },
  {
    id: 'unit-everyday-1',
    courseId: 'course-everyday',
    title: 'Food & Delivery',
    description: 'Restaurants, 배달 apps and convenience stores.',
    orderIndex: 1,
  },
  {
    id: 'unit-everyday-2',
    courseId: 'course-everyday',
    title: 'Getting Around',
    description: 'Subway, buses and taxis in Seoul.',
    orderIndex: 2,
  },
  {
    id: 'unit-everyday-3',
    courseId: 'course-everyday',
    title: 'Shopping',
    description: 'Sizes, prices and asking for help.',
    orderIndex: 3,
  },
  {
    id: 'unit-conversation-1',
    courseId: 'course-conversation',
    title: 'Making Friends',
    description: 'Small talk that does not feel like a textbook.',
    orderIndex: 1,
  },
  {
    id: 'unit-living-1',
    courseId: 'course-living',
    title: 'Daily Errands',
    description: 'Banks, post offices and package pickup.',
    orderIndex: 1,
  },
  {
    id: 'unit-travel-1',
    courseId: 'course-travel',
    title: 'Arrival',
    description: 'Airport, transport cards and checking in.',
    orderIndex: 1,
  },
  {
    id: 'unit-work-1',
    courseId: 'course-work',
    title: 'Office Korean',
    description: 'Greeting colleagues and joining a meeting.',
    orderIndex: 1,
  },
  {
    id: 'unit-conversation-2',
    courseId: 'course-conversation',
    title: 'Opinions & Feelings',
    description: 'Say what you think without sounding blunt.',
    orderIndex: 2,
  },
  {
    id: 'unit-conversation-3',
    courseId: 'course-conversation',
    title: 'Making Plans',
    description: 'Invite, reschedule and politely decline.',
    orderIndex: 3,
  },
  {
    id: 'unit-living-2',
    courseId: 'course-living',
    title: 'Health & Emergencies',
    description: 'Pharmacies, clinics and asking for help.',
    orderIndex: 2,
  },
  {
    id: 'unit-living-3',
    courseId: 'course-living',
    title: 'Home & Bills',
    description: 'Landlords, wifi, and the monthly 관리비.',
    orderIndex: 3,
  },
  {
    id: 'unit-travel-2',
    courseId: 'course-travel',
    title: 'Hotels & Stays',
    description: 'Check in, ask for late checkout, report a problem.',
    orderIndex: 2,
  },
  {
    id: 'unit-travel-3',
    courseId: 'course-travel',
    title: 'Sightseeing',
    description: 'Tickets, photos and asking locals for tips.',
    orderIndex: 3,
  },
  {
    id: 'unit-work-2',
    courseId: 'course-work',
    title: 'Email & Messages',
    description: 'Written Korean that reads professional.',
    orderIndex: 2,
  },
];

export const LESSONS: Lesson[] = [
  {
    id: 'lesson-greetings-hello',
    unitId: 'unit-starter-1',
    title: 'Hello & Goodbye',
    description: 'The two phrases you will use every single day.',
    lessonType: 'conversation',
    estimatedMinutes: 5,
    orderIndex: 1,
    isPremium: false,
  },
  {
    id: 'lesson-greetings-yesno',
    unitId: 'unit-starter-1',
    title: 'Yes & No',
    description: 'Agree, disagree and sound natural doing it.',
    lessonType: 'vocabulary',
    estimatedMinutes: 5,
    orderIndex: 2,
    isPremium: false,
  },
  {
    id: 'lesson-greetings-thanks',
    unitId: 'unit-starter-1',
    title: 'Thank You',
    description: 'Say thanks and reply when someone thanks you.',
    lessonType: 'conversation',
    estimatedMinutes: 5,
    orderIndex: 3,
    isPremium: false,
  },
  {
    id: 'lesson-greetings-intro',
    unitId: 'unit-starter-1',
    title: 'Introducing Yourself',
    description: 'Name, country and a friendly first impression.',
    lessonType: 'conversation',
    estimatedMinutes: 7,
    orderIndex: 4,
    isPremium: false,
  },
  {
    id: 'lesson-cafe-coffee',
    unitId: 'unit-starter-2',
    title: 'Ordering Coffee',
    description: 'Order an americano without switching to English.',
    lessonType: 'conversation',
    estimatedMinutes: 5,
    orderIndex: 1,
    isPremium: false,
  },
  {
    id: 'lesson-cafe-water',
    unitId: 'unit-starter-2',
    title: 'Asking for Water',
    description: 'Ask for water, napkins and a to-go cup.',
    lessonType: 'vocabulary',
    estimatedMinutes: 5,
    orderIndex: 2,
    isPremium: false,
  },
  {
    id: 'lesson-cafe-paying',
    unitId: 'unit-starter-2',
    title: 'Paying',
    description: 'Card, cash and points — the whole counter script.',
    lessonType: 'conversation',
    estimatedMinutes: 6,
    orderIndex: 3,
    isPremium: false,
  },
  {
    id: 'lesson-hangul-consonants',
    unitId: 'unit-starter-3',
    title: 'Hangul Consonants',
    description: 'The 14 basic consonants and how they sound.',
    lessonType: 'hangul',
    estimatedMinutes: 8,
    orderIndex: 1,
    isPremium: false,
  },
  {
    id: 'lesson-hangul-vowels',
    unitId: 'unit-starter-3',
    title: 'Hangul Vowels',
    description: 'Ten vowels built from three simple strokes.',
    lessonType: 'hangul',
    estimatedMinutes: 8,
    orderIndex: 2,
    isPremium: false,
  },
  {
    id: 'lesson-numbers-sino',
    unitId: 'unit-starter-4',
    title: 'Numbers for Money',
    description: 'Sino-Korean numbers for prices and dates.',
    lessonType: 'vocabulary',
    estimatedMinutes: 6,
    orderIndex: 1,
    isPremium: false,
  },
  {
    id: 'lesson-numbers-native',
    unitId: 'unit-starter-4',
    title: 'Counting Things',
    description: 'Native Korean numbers for cups, people and hours.',
    lessonType: 'vocabulary',
    estimatedMinutes: 6,
    orderIndex: 2,
    isPremium: false,
  },
  {
    id: 'lesson-food-restaurant',
    unitId: 'unit-everyday-1',
    title: 'At a Restaurant',
    description: 'Order for the table and ask for the check.',
    lessonType: 'conversation',
    estimatedMinutes: 7,
    orderIndex: 1,
    isPremium: false,
  },
  {
    id: 'lesson-food-convenience',
    unitId: 'unit-everyday-1',
    title: 'Convenience Store',
    description: 'The 편의점 phrases nobody teaches you.',
    lessonType: 'conversation',
    estimatedMinutes: 6,
    orderIndex: 2,
    isPremium: false,
  },
  {
    id: 'lesson-transport-subway',
    unitId: 'unit-everyday-2',
    title: 'Taking the Subway',
    description: 'Transfers, exits and asking which line.',
    lessonType: 'conversation',
    estimatedMinutes: 7,
    orderIndex: 1,
    isPremium: false,
  },
  {
    id: 'lesson-transport-taxi',
    unitId: 'unit-everyday-2',
    title: 'Taking a Taxi',
    description: 'Give an address and ask to stop here.',
    lessonType: 'conversation',
    estimatedMinutes: 6,
    orderIndex: 2,
    isPremium: true,
  },
  {
    id: 'lesson-shopping-sizes',
    unitId: 'unit-everyday-3',
    title: 'Sizes & Colors',
    description: 'Try it on and ask for another size.',
    lessonType: 'vocabulary',
    estimatedMinutes: 6,
    orderIndex: 1,
    isPremium: true,
  },
  {
    id: 'lesson-conversation-smalltalk',
    unitId: 'unit-conversation-1',
    title: 'Small Talk',
    description: 'Weather, weekends and what you did yesterday.',
    lessonType: 'conversation',
    estimatedMinutes: 8,
    orderIndex: 1,
    isPremium: true,
  },
  {
    id: 'lesson-living-delivery',
    unitId: 'unit-living-1',
    title: 'Package Delivery',
    description: 'Talk to the 택배 driver and the front desk.',
    lessonType: 'conversation',
    estimatedMinutes: 7,
    orderIndex: 1,
    isPremium: true,
  },
  {
    id: 'lesson-travel-airport',
    unitId: 'unit-travel-1',
    title: 'At the Airport',
    description: 'Immigration, T-money and the airport bus.',
    lessonType: 'conversation',
    estimatedMinutes: 7,
    orderIndex: 1,
    isPremium: true,
  },
  {
    id: 'lesson-work-greetings',
    unitId: 'unit-work-1',
    title: 'Office Greetings',
    description: '수고하셨습니다 and when to actually use it.',
    lessonType: 'culture',
    estimatedMinutes: 6,
    orderIndex: 1,
    isPremium: true,
  },
  {
    id: 'lesson-conversation-opinions',
    unitId: 'unit-conversation-2',
    title: 'Giving an Opinion',
    description: 'Agree, disagree and soften it the Korean way.',
    lessonType: 'conversation',
    estimatedMinutes: 8,
    orderIndex: 1,
    isPremium: true,
  },
  {
    id: 'lesson-conversation-feelings',
    unitId: 'unit-conversation-2',
    title: 'Talking About Feelings',
    description: 'Tired, excited, stressed — say it naturally.',
    lessonType: 'vocabulary',
    estimatedMinutes: 7,
    orderIndex: 2,
    isPremium: true,
  },
  {
    id: 'lesson-conversation-plans',
    unitId: 'unit-conversation-3',
    title: 'Making Plans',
    description: 'Suggest a time and place without over-explaining.',
    lessonType: 'conversation',
    estimatedMinutes: 8,
    orderIndex: 1,
    isPremium: true,
  },
  {
    id: 'lesson-conversation-declining',
    unitId: 'unit-conversation-3',
    title: 'Saying No Politely',
    description: 'Decline an invitation without any awkwardness.',
    lessonType: 'culture',
    estimatedMinutes: 7,
    orderIndex: 2,
    isPremium: true,
  },
  {
    id: 'lesson-living-pharmacy',
    unitId: 'unit-living-2',
    title: 'At the Pharmacy',
    description: 'Describe a symptom and get the right medicine.',
    lessonType: 'conversation',
    estimatedMinutes: 8,
    orderIndex: 1,
    isPremium: true,
  },
  {
    id: 'lesson-living-emergency',
    unitId: 'unit-living-2',
    title: 'Getting Help Fast',
    description: 'The few sentences you hope never to need.',
    lessonType: 'vocabulary',
    estimatedMinutes: 6,
    orderIndex: 2,
    isPremium: true,
  },
  {
    id: 'lesson-living-apartment',
    unitId: 'unit-living-3',
    title: 'Apartment Problems',
    description: 'Report a leak, no hot water or a broken lock.',
    lessonType: 'conversation',
    estimatedMinutes: 8,
    orderIndex: 1,
    isPremium: true,
  },
  {
    id: 'lesson-travel-hotel',
    unitId: 'unit-travel-2',
    title: 'Checking In',
    description: 'Reservations, luggage and late checkout.',
    lessonType: 'conversation',
    estimatedMinutes: 7,
    orderIndex: 1,
    isPremium: true,
  },
  {
    id: 'lesson-travel-sightseeing',
    unitId: 'unit-travel-3',
    title: 'Tickets & Photos',
    description: 'Buy entry, ask for a photo, find the good spot.',
    lessonType: 'conversation',
    estimatedMinutes: 7,
    orderIndex: 1,
    isPremium: true,
  },
  {
    id: 'lesson-work-email',
    unitId: 'unit-work-2',
    title: 'Writing a Work Message',
    description: 'Openers, requests and closings that read right.',
    lessonType: 'grammar',
    estimatedMinutes: 8,
    orderIndex: 1,
    isPremium: true,
  },
  {
    id: 'lesson-hangul-batchim',
    unitId: 'unit-starter-3',
    title: 'Batchim: Final Consonants',
    description: 'The consonant that lands at the bottom of a syllable.',
    lessonType: 'hangul',
    estimatedMinutes: 7,
    orderIndex: 3,
    isPremium: false,
  },
  {
    id: 'lesson-hangul-reading',
    unitId: 'unit-starter-3',
    title: 'Reading Real Words',
    description: 'Put the letters together and read signs on the street.',
    lessonType: 'hangul',
    estimatedMinutes: 8,
    orderIndex: 4,
    isPremium: false,
  },
  {
    id: 'lesson-hangul-tricky',
    unitId: 'unit-starter-3',
    title: 'Sounds That Trip People Up',
    description: 'ㅓ vs ㅗ, ㄹ, and the double consonants.',
    lessonType: 'hangul',
    estimatedMinutes: 7,
    orderIndex: 5,
    isPremium: false,
  },
  {
    id: 'lesson-numbers-time',
    unitId: 'unit-starter-4',
    title: 'Telling the Time',
    description: 'Both number systems in one sentence, and why.',
    lessonType: 'vocabulary',
    estimatedMinutes: 6,
    orderIndex: 3,
    isPremium: false,
  },
  {
    id: 'lesson-numbers-dates',
    unitId: 'unit-starter-4',
    title: 'Days & Dates',
    description: 'Months, days and making a plan for Friday.',
    lessonType: 'vocabulary',
    estimatedMinutes: 6,
    orderIndex: 4,
    isPremium: false,
  },
  {
    id: 'lesson-numbers-phone',
    unitId: 'unit-starter-4',
    title: 'Phone Numbers & Addresses',
    description: 'Read your number out loud without hesitating.',
    lessonType: 'vocabulary',
    estimatedMinutes: 5,
    orderIndex: 5,
    isPremium: false,
  },
  {
    id: 'lesson-food-delivery',
    unitId: 'unit-everyday-1',
    title: 'Ordering Delivery',
    description: '배달 apps, and where to leave the bag.',
    lessonType: 'conversation',
    estimatedMinutes: 6,
    orderIndex: 3,
    isPremium: false,
  },
  {
    id: 'lesson-food-spicy',
    unitId: 'unit-everyday-1',
    title: 'Spicy, Sweet, Salty',
    description: 'Describe food and ask for it milder.',
    lessonType: 'vocabulary',
    estimatedMinutes: 5,
    orderIndex: 4,
    isPremium: false,
  },
  {
    id: 'lesson-food-bill',
    unitId: 'unit-everyday-1',
    title: 'Paying the Bill',
    description: 'Split it, card it, and leave properly.',
    lessonType: 'conversation',
    estimatedMinutes: 5,
    orderIndex: 5,
    isPremium: false,
  },
  {
    id: 'lesson-transport-bus',
    unitId: 'unit-everyday-2',
    title: 'Buses & Transfers',
    description: 'Tag on, tag off, and change lines.',
    lessonType: 'conversation',
    estimatedMinutes: 6,
    orderIndex: 3,
    isPremium: false,
  },
  {
    id: 'lesson-transport-directions',
    unitId: 'unit-everyday-2',
    title: 'Asking for Directions',
    description: 'Left, right, straight, and how far.',
    lessonType: 'conversation',
    estimatedMinutes: 6,
    orderIndex: 4,
    isPremium: false,
  },
  {
    id: 'lesson-transport-lost',
    unitId: 'unit-everyday-2',
    title: 'When You Are Lost',
    description: 'Ask for help without panicking.',
    lessonType: 'conversation',
    estimatedMinutes: 5,
    orderIndex: 5,
    isPremium: false,
  },
  {
    id: 'lesson-shopping-asking',
    unitId: 'unit-everyday-3',
    title: 'Asking for Help',
    description: 'Find it, try it, and ask what it costs.',
    lessonType: 'conversation',
    estimatedMinutes: 5,
    orderIndex: 2,
    isPremium: false,
  },
  {
    id: 'lesson-shopping-paying',
    unitId: 'unit-everyday-3',
    title: 'Paying & Receipts',
    description: 'Card, cash, bag, receipt.',
    lessonType: 'conversation',
    estimatedMinutes: 5,
    orderIndex: 3,
    isPremium: false,
  },
  {
    id: 'lesson-shopping-returns',
    unitId: 'unit-everyday-3',
    title: 'Exchanges & Returns',
    description: 'Change the size or get your money back.',
    lessonType: 'conversation',
    estimatedMinutes: 6,
    orderIndex: 4,
    isPremium: false,
  },
  {
    id: 'lesson-shopping-market',
    unitId: 'unit-everyday-3',
    title: 'At the Market',
    description: 'Traditional markets, and asking for a little less.',
    lessonType: 'conversation',
    estimatedMinutes: 6,
    orderIndex: 5,
    isPremium: false,
  },
  {
    id: 'lesson-friends-smalltalk',
    unitId: 'unit-conversation-1',
    title: 'Small Talk That Works',
    description: 'Weather, food, weekend — the three safe openers.',
    lessonType: 'conversation',
    estimatedMinutes: 6,
    orderIndex: 2,
    isPremium: true,
  },
  {
    id: 'lesson-friends-banmal',
    unitId: 'unit-conversation-1',
    title: 'Dropping the 요',
    description: 'When to switch to casual speech, and how to ask.',
    lessonType: 'grammar',
    estimatedMinutes: 7,
    orderIndex: 3,
    isPremium: true,
  },
  {
    id: 'lesson-friends-kakao',
    unitId: 'unit-conversation-1',
    title: 'Texting Like a Local',
    description: 'ㅋㅋㅋ, ㅇㅇ, 넵 — how Koreans actually type.',
    lessonType: 'vocabulary',
    estimatedMinutes: 6,
    orderIndex: 4,
    isPremium: true,
  },
  {
    id: 'lesson-friends-compliments',
    unitId: 'unit-conversation-1',
    title: 'Compliments & Reactions',
    description: 'React like you mean it: 대박, 진짜?, 완전.',
    lessonType: 'conversation',
    estimatedMinutes: 5,
    orderIndex: 5,
    isPremium: true,
  },
  {
    id: 'lesson-opinions-agree',
    unitId: 'unit-conversation-2',
    title: 'Agreeing & Disagreeing',
    description: 'Say no without sounding blunt.',
    lessonType: 'conversation',
    estimatedMinutes: 6,
    orderIndex: 3,
    isPremium: true,
  },
  {
    id: 'lesson-opinions-because',
    unitId: 'unit-conversation-2',
    title: 'Giving Reasons',
    description: '~아서/어서 and ~니까: because, two ways.',
    lessonType: 'grammar',
    estimatedMinutes: 7,
    orderIndex: 4,
    isPremium: true,
  },
  {
    id: 'lesson-opinions-maybe',
    unitId: 'unit-conversation-2',
    title: 'Softening What You Say',
    description: '아마, 좀, ~것 같아요 — the Korean art of hedging.',
    lessonType: 'grammar',
    estimatedMinutes: 7,
    orderIndex: 5,
    isPremium: true,
  },
  {
    id: 'lesson-plans-invite',
    unitId: 'unit-conversation-3',
    title: 'Inviting Someone Out',
    description: 'Ask without putting them on the spot.',
    lessonType: 'conversation',
    estimatedMinutes: 6,
    orderIndex: 3,
    isPremium: true,
  },
  {
    id: 'lesson-plans-cancel',
    unitId: 'unit-conversation-3',
    title: 'Changing Plans',
    description: 'Postpone or cancel without burning the friendship.',
    lessonType: 'conversation',
    estimatedMinutes: 6,
    orderIndex: 4,
    isPremium: true,
  },
  {
    id: 'lesson-plans-confirm',
    unitId: 'unit-conversation-3',
    title: 'Confirming Details',
    description: 'Time, place, and who else is coming.',
    lessonType: 'conversation',
    estimatedMinutes: 5,
    orderIndex: 5,
    isPremium: true,
  },
  {
    id: 'lesson-errands-bank',
    unitId: 'unit-living-1',
    title: 'At the Bank',
    description: 'Open an account and understand the questions.',
    lessonType: 'conversation',
    estimatedMinutes: 7,
    orderIndex: 2,
    isPremium: true,
  },
  {
    id: 'lesson-errands-post',
    unitId: 'unit-living-1',
    title: 'Post Office & Parcels',
    description: 'Send it, track it, collect it.',
    lessonType: 'conversation',
    estimatedMinutes: 6,
    orderIndex: 3,
    isPremium: true,
  },
  {
    id: 'lesson-errands-phone',
    unitId: 'unit-living-1',
    title: 'Getting a Phone Plan',
    description: 'Contracts, data, and what to ask for.',
    lessonType: 'conversation',
    estimatedMinutes: 7,
    orderIndex: 4,
    isPremium: true,
  },
  {
    id: 'lesson-errands-haircut',
    unitId: 'unit-living-1',
    title: 'At the Hair Salon',
    description: 'Explain the cut you actually want.',
    lessonType: 'conversation',
    estimatedMinutes: 6,
    orderIndex: 5,
    isPremium: true,
  },
  {
    id: 'lesson-health-pharmacy',
    unitId: 'unit-living-2',
    title: 'At the Pharmacy',
    description: 'Describe a symptom and get the right thing.',
    lessonType: 'conversation',
    estimatedMinutes: 6,
    orderIndex: 3,
    isPremium: true,
  },
  {
    id: 'lesson-health-emergency',
    unitId: 'unit-living-2',
    title: 'Emergencies',
    description: '119, 112, and the sentences that matter most.',
    lessonType: 'conversation',
    estimatedMinutes: 6,
    orderIndex: 4,
    isPremium: true,
  },
  {
    id: 'lesson-health-appointment',
    unitId: 'unit-living-2',
    title: 'Making an Appointment',
    description: 'Book a doctor, dentist or check-up.',
    lessonType: 'conversation',
    estimatedMinutes: 5,
    orderIndex: 5,
    isPremium: true,
  },
  {
    id: 'lesson-home-contract',
    unitId: 'unit-living-3',
    title: 'Renting an Apartment',
    description: '월세, 전세, 보증금 — what you are agreeing to.',
    lessonType: 'vocabulary',
    estimatedMinutes: 8,
    orderIndex: 2,
    isPremium: true,
  },
  {
    id: 'lesson-home-utilities',
    unitId: 'unit-living-3',
    title: 'Bills & Utilities',
    description: 'Gas, electricity, internet, and the maintenance fee.',
    lessonType: 'vocabulary',
    estimatedMinutes: 6,
    orderIndex: 3,
    isPremium: true,
  },
  {
    id: 'lesson-home-neighbours',
    unitId: 'unit-living-3',
    title: 'Neighbours & Building Rules',
    description: 'Rubbish days, noise, and the 경비 아저씨.',
    lessonType: 'conversation',
    estimatedMinutes: 6,
    orderIndex: 4,
    isPremium: true,
  },
  {
    id: 'lesson-home-repairs',
    unitId: 'unit-living-3',
    title: 'When Something Breaks',
    description: 'Report it and get it fixed.',
    lessonType: 'conversation',
    estimatedMinutes: 6,
    orderIndex: 5,
    isPremium: true,
  },
  {
    id: 'lesson-arrival-immigration',
    unitId: 'unit-travel-1',
    title: 'Immigration & Customs',
    description: 'Answer the questions without hesitating.',
    lessonType: 'conversation',
    estimatedMinutes: 6,
    orderIndex: 2,
    isPremium: true,
  },
  {
    id: 'lesson-arrival-transport',
    unitId: 'unit-travel-1',
    title: 'Getting Into the City',
    description: 'Airport bus, AREX, or taxi.',
    lessonType: 'conversation',
    estimatedMinutes: 6,
    orderIndex: 3,
    isPremium: true,
  },
  {
    id: 'lesson-arrival-simcard',
    unitId: 'unit-travel-1',
    title: 'SIM Cards & Wifi',
    description: 'Get online in the first ten minutes.',
    lessonType: 'conversation',
    estimatedMinutes: 5,
    orderIndex: 4,
    isPremium: true,
  },
  {
    id: 'lesson-hotel-checkin',
    unitId: 'unit-travel-2',
    title: 'Checking In',
    description: 'Reservation, ID, and what time breakfast is.',
    lessonType: 'conversation',
    estimatedMinutes: 6,
    orderIndex: 2,
    isPremium: true,
  },
  {
    id: 'lesson-hotel-problems',
    unitId: 'unit-travel-2',
    title: 'When the Room Is Wrong',
    description: 'Too hot, too loud, or missing something.',
    lessonType: 'conversation',
    estimatedMinutes: 6,
    orderIndex: 3,
    isPremium: true,
  },
  {
    id: 'lesson-hotel-checkout',
    unitId: 'unit-travel-2',
    title: 'Checking Out',
    description: 'Luggage storage and the late checkout ask.',
    lessonType: 'conversation',
    estimatedMinutes: 5,
    orderIndex: 4,
    isPremium: true,
  },
  {
    id: 'lesson-sights-tickets',
    unitId: 'unit-travel-3',
    title: 'Tickets & Entry',
    description: 'Buy, queue, and ask about discounts.',
    lessonType: 'conversation',
    estimatedMinutes: 5,
    orderIndex: 2,
    isPremium: true,
  },
  {
    id: 'lesson-sights-photos',
    unitId: 'unit-travel-3',
    title: 'Photos & Politeness',
    description: 'Ask before you shoot, and offer to take theirs.',
    lessonType: 'conversation',
    estimatedMinutes: 5,
    orderIndex: 3,
    isPremium: true,
  },
  {
    id: 'lesson-sights-recommend',
    unitId: 'unit-travel-3',
    title: 'Asking for Recommendations',
    description: 'Find the place locals actually go.',
    lessonType: 'conversation',
    estimatedMinutes: 6,
    orderIndex: 4,
    isPremium: true,
  },
  {
    id: 'lesson-office-greetings',
    unitId: 'unit-work-1',
    title: 'Office Etiquette',
    description: '수고하셨습니다 and when to say it.',
    lessonType: 'conversation',
    estimatedMinutes: 6,
    orderIndex: 2,
    isPremium: true,
  },
  {
    id: 'lesson-office-meetings',
    unitId: 'unit-work-1',
    title: 'In a Meeting',
    description: 'Agree, ask for time, and close a point.',
    lessonType: 'conversation',
    estimatedMinutes: 7,
    orderIndex: 3,
    isPremium: true,
  },
  {
    id: 'lesson-office-requests',
    unitId: 'unit-work-1',
    title: 'Asking Colleagues for Things',
    description: 'Requests that do not sound like orders.',
    lessonType: 'grammar',
    estimatedMinutes: 7,
    orderIndex: 4,
    isPremium: true,
  },
  {
    id: 'lesson-office-hoesik',
    unitId: 'unit-work-1',
    title: 'Team Dinners',
    description: '회식 survival: pouring, toasting, leaving.',
    lessonType: 'culture',
    estimatedMinutes: 6,
    orderIndex: 5,
    isPremium: true,
  },
  {
    id: 'lesson-email-open',
    unitId: 'unit-work-2',
    title: 'Writing an Email',
    description: 'Openings, closings and the 님 you must not forget.',
    lessonType: 'vocabulary',
    estimatedMinutes: 7,
    orderIndex: 2,
    isPremium: true,
  },
  {
    id: 'lesson-email-request',
    unitId: 'unit-work-2',
    title: 'Making a Request in Writing',
    description: 'Ask for a deadline, a file, or a favour.',
    lessonType: 'vocabulary',
    estimatedMinutes: 7,
    orderIndex: 3,
    isPremium: true,
  },
  {
    id: 'lesson-email-apology',
    unitId: 'unit-work-2',
    title: 'Apologising Professionally',
    description: 'Late, wrong, or missing — say it properly.',
    lessonType: 'vocabulary',
    estimatedMinutes: 6,
    orderIndex: 4,
    isPremium: true,
  },
  {
    id: 'lesson-email-messenger',
    unitId: 'unit-work-2',
    title: 'Work Messenger',
    description: 'Short, fast, and still polite.',
    lessonType: 'vocabulary',
    estimatedMinutes: 5,
    orderIndex: 5,
    isPremium: true,
  },
];
