import type { DailyPhrase } from '@/types/content';

export const DAILY_PHRASES: DailyPhrase[] = [
  { id: 'dp-01', korean: '오늘 뭐 해요?', english: 'What are you doing today?', romanization: 'oneul mwo haeyo?', category: 'friends', audioUrl: null, publishDate: '2025-01-01' },
  { id: 'dp-02', korean: '아메리카노 한 잔 주세요.', english: 'One americano, please.', romanization: 'amerikano han jan juseyo.', category: 'food', audioUrl: null, publishDate: '2025-01-02' },
  { id: 'dp-03', korean: '진짜 대박이에요!', english: "That's awesome!", romanization: 'jinjja daebagieyo!', category: 'slang', audioUrl: null, publishDate: '2025-01-03' },
  { id: 'dp-04', korean: '밥 먹었어요?', english: 'Have you eaten?', romanization: 'bap meogeosseoyo?', category: 'culture', audioUrl: null, publishDate: '2025-01-04' },
  { id: 'dp-05', korean: '천천히 말해 주세요.', english: 'Please speak slowly.', romanization: 'cheoncheonhi malhae juseyo.', category: 'travel', audioUrl: null, publishDate: '2025-01-05' },
  { id: 'dp-06', korean: '우리 언제 만날까요?', english: 'When should we meet?', romanization: 'uri eonje mannalkkayo?', category: 'dating', audioUrl: null, publishDate: '2025-01-06' },
  { id: 'dp-07', korean: '수고하셨습니다.', english: 'Good work today.', romanization: 'sugohasyeotseumnida.', category: 'work', audioUrl: null, publishDate: '2025-01-07' },
  { id: 'dp-08', korean: '이거 진짜 맛있어요.', english: 'This is really delicious.', romanization: 'igeo jinjja masisseoyo.', category: 'food', audioUrl: null, publishDate: '2025-01-08' },
  { id: 'dp-09', korean: '화장실이 어디예요?', english: 'Where is the bathroom?', romanization: 'hwajangsiri eodiyeyo?', category: 'travel', audioUrl: null, publishDate: '2025-01-09' },
  { id: 'dp-10', korean: '오늘 시간 있어요?', english: 'Do you have time today?', romanization: 'oneul sigan isseoyo?', category: 'dating', audioUrl: null, publishDate: '2025-01-10' },
  { id: 'dp-11', korean: '완전 좋아요!', english: 'I totally love it!', romanization: 'wanjeon joayo!', category: 'slang', audioUrl: null, publishDate: '2025-01-11' },
  { id: 'dp-12', korean: '조심히 가세요.', english: 'Get home safely.', romanization: 'josimhi gaseyo.', category: 'culture', audioUrl: null, publishDate: '2025-01-12' },
  { id: 'dp-13', korean: '내일 회의 있어요.', english: 'There is a meeting tomorrow.', romanization: 'naeil hoeui isseoyo.', category: 'work', audioUrl: null, publishDate: '2025-01-13' },
  { id: 'dp-14', korean: '같이 갈래요?', english: 'Do you want to go together?', romanization: 'gachi gallaeyo?', category: 'friends', audioUrl: null, publishDate: '2025-01-14' },
  { id: 'dp-15', korean: '여기서 세워 주세요.', english: 'Please stop here.', romanization: 'yeogiseo sewo juseyo.', category: 'travel', audioUrl: null, publishDate: '2025-01-15' },
  { id: 'dp-16', korean: '커피 한잔할래요?', english: 'Want to grab a coffee?', romanization: 'keopi hanjanhallaeyo?', category: 'dating', audioUrl: null, publishDate: '2025-01-16' },
  { id: 'dp-17', korean: '진짜요?', english: 'Really?', romanization: 'jinjjayo?', category: 'friends', audioUrl: null, publishDate: '2025-01-17' },
  { id: 'dp-18', korean: '배고파 죽겠어요.', english: "I'm starving.", romanization: 'baegopa jukgesseoyo.', category: 'slang', audioUrl: null, publishDate: '2025-01-18' },
  { id: 'dp-19', korean: '이따 봐요.', english: 'See you later.', romanization: 'itta bwayo.', category: 'friends', audioUrl: null, publishDate: '2025-01-19' },
  { id: 'dp-20', korean: '포장해 주세요.', english: 'To go, please.', romanization: 'pojanghae juseyo.', category: 'food', audioUrl: null, publishDate: '2025-01-20' },
  { id: 'dp-21', korean: '카드로 할게요.', english: "I'll pay by card.", romanization: 'kadeuro halgeyo.', category: 'food', audioUrl: null, publishDate: '2025-01-21' },
  { id: 'dp-22', korean: '몇 번 출구예요?', english: 'Which exit number is it?', romanization: 'myeot beon chulguyeyo?', category: 'travel', audioUrl: null, publishDate: '2025-01-22' },
  { id: 'dp-23', korean: '내일 뭐 해요?', english: 'What are you doing tomorrow?', romanization: 'naeil mwo haeyo?', category: 'dating', audioUrl: null, publishDate: '2025-01-23' },
  { id: 'dp-24', korean: '조금만 기다려 주세요.', english: 'Please wait just a moment.', romanization: 'jogeumman gidaryeo juseyo.', category: 'work', audioUrl: null, publishDate: '2025-01-24' },
  { id: 'dp-25', korean: '완전 꿀잼이에요.', english: "It's so much fun.", romanization: 'wanjeon kkuljaemieyo.', category: 'slang', audioUrl: null, publishDate: '2025-01-25' },
  { id: 'dp-26', korean: '한 살 차이도 형이에요.', english: 'Even one year older makes them your elder.', romanization: 'han sal chaido hyeongieyo.', category: 'culture', audioUrl: null, publishDate: '2025-01-26' },
  { id: 'dp-27', korean: '덜 맵게 해 주세요.', english: 'Please make it less spicy.', romanization: 'deol maepge hae juseyo.', category: 'food', audioUrl: null, publishDate: '2025-01-27' },
  { id: 'dp-28', korean: '와이파이 비밀번호가 뭐예요?', english: "What's the wifi password?", romanization: 'waipai bimilbeonhoga mwoyeyo?', category: 'travel', audioUrl: null, publishDate: '2025-01-28' },
  { id: 'dp-29', korean: '먼저 들어가 보겠습니다.', english: "I'll head out first.", romanization: 'meonjeo deureoga bogesseumnida.', category: 'work', audioUrl: null, publishDate: '2025-01-29' },
  { id: 'dp-30', korean: '연락할게요.', english: "I'll text you.", romanization: 'yeollakhalgeyo.', category: 'dating', audioUrl: null, publishDate: '2025-01-30' },
  { id: 'dp-31', korean: '무슨 일 있어요?', english: 'Is something wrong?', romanization: 'museun il isseoyo?', category: 'friends', audioUrl: null, publishDate: '2025-01-31' },
  { id: 'dp-32', korean: '리필 되나요?', english: 'Can I get a refill?', romanization: 'ripil doenayo?', category: 'food', audioUrl: null, publishDate: '2025-02-01' },
  { id: 'dp-33', korean: '길 좀 물어봐도 될까요?', english: 'Could I ask you for directions?', romanization: 'gil jom mureobwado doelkkayo?', category: 'travel', audioUrl: null, publishDate: '2025-02-02' },
  { id: 'dp-34', korean: '그럴 수도 있죠.', english: 'That could happen, I guess.', romanization: 'geureol sudo itjyo.', category: 'friends', audioUrl: null, publishDate: '2025-02-03' },
  { id: 'dp-35', korean: '회식 있어요?', english: 'Is there a team dinner?', romanization: 'hoesik isseoyo?', category: 'work', audioUrl: null, publishDate: '2025-02-04' },
  { id: 'dp-36', korean: '심쿵했어요.', english: 'My heart skipped a beat.', romanization: 'simkunghaesseoyo.', category: 'slang', audioUrl: null, publishDate: '2025-02-05' },
  { id: 'dp-37', korean: '신발 벗고 들어오세요.', english: 'Please take your shoes off.', romanization: 'sinbal beotgo deureooseyo.', category: 'culture', audioUrl: null, publishDate: '2025-02-06' },
  { id: 'dp-38', korean: '얼마나 걸려요?', english: 'How long does it take?', romanization: 'eolmana geollyeoyo?', category: 'travel', audioUrl: null, publishDate: '2025-02-07' },
  { id: 'dp-39', korean: '제가 살게요.', english: "It's on me.", romanization: 'jega salgeyo.', category: 'friends', audioUrl: null, publishDate: '2025-02-08' },
  { id: 'dp-40', korean: '다음에 또 올게요.', english: "I'll come again next time.", romanization: 'daeume tto olgeyo.', category: 'food', audioUrl: null, publishDate: '2025-02-09' },
  { id: 'dp-41', korean: '오늘 진짜 예쁘네요.', english: 'You look really nice today.', romanization: 'oneul jinjja yeppeuneyo.', category: 'dating', audioUrl: null, publishDate: '2025-02-10' },
  { id: 'dp-42', korean: '확인해 보고 말씀드릴게요.', english: "I'll check and get back to you.", romanization: 'hwaginhae bogo malsseumdeurilgeyo.', category: 'work', audioUrl: null, publishDate: '2025-02-11' },
  { id: 'dp-43', korean: '노잼이에요.', english: "It's boring.", romanization: 'nojaemieyo.', category: 'slang', audioUrl: null, publishDate: '2025-02-12' },
  { id: 'dp-44', korean: '나이가 어떻게 되세요?', english: 'How old are you?', romanization: 'naiga eotteoke doeseyo?', category: 'culture', audioUrl: null, publishDate: '2025-02-13' },
  { id: 'dp-45', korean: '이거 하나만 더 주세요.', english: 'One more of these, please.', romanization: 'igeo hanaman deo juseyo.', category: 'food', audioUrl: null, publishDate: '2025-02-14' },
  { id: 'dp-46', korean: '환승하려면 어디로 가요?', english: 'Where do I go to transfer?', romanization: 'hwanseunghaeryeomyeon eodiro gayo?', category: 'travel', audioUrl: null, publishDate: '2025-02-15' },
  { id: 'dp-47', korean: '잘 지냈어요?', english: 'How have you been?', romanization: 'jal jinaesseoyo?', category: 'friends', audioUrl: null, publishDate: '2025-02-16' },
  { id: 'dp-48', korean: '오늘 야근이에요.', english: "I'm working late today.", romanization: 'oneul yageunieyo.', category: 'work', audioUrl: null, publishDate: '2025-02-17' },
  { id: 'dp-49', korean: '우리 사귈래요?', english: 'Do you want to go out with me?', romanization: 'uri sagwillaeyo?', category: 'dating', audioUrl: null, publishDate: '2025-02-18' },
  { id: 'dp-50', korean: '갑분싸.', english: 'The mood suddenly died.', romanization: 'gapbunssa.', category: 'slang', audioUrl: null, publishDate: '2025-02-19' },
  { id: 'dp-51', korean: '나이 들면 한 살 더 먹어요.', english: 'On New Year everyone turns a year older.', romanization: 'nai deulmyeon han sal deo meogeoyo.', category: 'culture', audioUrl: null, publishDate: '2025-02-20' },
  { id: 'dp-52', korean: '여기 앉아도 돼요?', english: 'May I sit here?', romanization: 'yeogi anjado dwaeyo?', category: 'travel', audioUrl: null, publishDate: '2025-02-21' },
  { id: 'dp-53', korean: '배달 시킬까요?', english: 'Shall we order delivery?', romanization: 'baedal sikilkkayo?', category: 'food', audioUrl: null, publishDate: '2025-02-22' },
  { id: 'dp-54', korean: '괜찮아요, 신경 쓰지 마세요.', english: "It's fine, don't worry about it.", romanization: 'gwaenchanayo, singyeong sseuji maseyo.', category: 'friends', audioUrl: null, publishDate: '2025-02-23' },
  { id: 'dp-55', korean: '자리 있어요?', english: 'Is this seat taken?', romanization: 'jari isseoyo?', category: 'food', audioUrl: null, publishDate: '2025-02-24' },
  { id: 'dp-56', korean: '조심히 들어가세요.', english: 'Get home safely.', romanization: 'josimhi deureogaseyo.', category: 'culture', audioUrl: null, publishDate: '2025-02-25' },
  { id: 'dp-57', korean: '회의 몇 시예요?', english: 'What time is the meeting?', romanization: 'hoeui myeot siyeyo?', category: 'work', audioUrl: null, publishDate: '2025-02-26' },
  { id: 'dp-58', korean: '보고 싶었어요.', english: 'I missed you.', romanization: 'bogo sipeosseoyo.', category: 'dating', audioUrl: null, publishDate: '2025-02-27' },
  { id: 'dp-59', korean: '아 진짜 킹받네.', english: 'Ugh, that is so annoying.', romanization: 'a jinjja kingbanne.', category: 'slang', audioUrl: null, publishDate: '2025-02-28' },
  { id: 'dp-60', korean: '수고했어요.', english: 'Good job / thanks for your work.', romanization: 'sugohaesseoyo.', category: 'work', audioUrl: null, publishDate: '2025-03-01' },
];

/** Rotates through the phrase list so every day shows a different phrase. */
export function getDailyPhrase(date: Date = new Date()): DailyPhrase {
  const daysSinceEpoch = Math.floor(date.getTime() / 86_400_000);
  return DAILY_PHRASES[Math.abs(daysSinceEpoch) % DAILY_PHRASES.length];
}
