import type { ChatSituation } from '@/types/content';

export const CHAT_SITUATIONS: ChatSituation[] = [
  {
    id: 'cafe',
    title: 'Cafe',
    emoji: '☕',
    description: 'Order a drink and answer the barista.',
    openingLine: { korean: '안녕하세요! 주문하시겠어요?', english: 'Hello! Would you like to order?', romanization: 'annyeonghaseyo! jumunhasigesseoyo?' },
    isPremium: false,
  },
  {
    id: 'restaurant',
    title: 'Restaurant',
    emoji: '🍚',
    description: 'Order for the table and ask for the bill.',
    openingLine: { korean: '어서 오세요! 몇 분이세요?', english: 'Welcome! How many people?', romanization: 'eoseo oseyo! myeot buniseyo?' },
    isPremium: false,
  },
  {
    id: 'convenience',
    title: 'Convenience Store',
    emoji: '🏪',
    description: 'Pay, decline a bag, heat up your food.',
    openingLine: { korean: '안녕하세요. 봉투 필요하세요?', english: 'Hello. Do you need a bag?', romanization: 'annyeonghaseyo. bongtu piryohaseyo?' },
    isPremium: false,
  },
  {
    id: 'taxi',
    title: 'Taxi',
    emoji: '🚕',
    description: 'Give an address and ask to stop.',
    openingLine: { korean: '어디로 모실까요?', english: 'Where shall I take you?', romanization: 'eodiro mosilkkayo?' },
    isPremium: true,
  },
  {
    id: 'airport',
    title: 'Airport',
    emoji: '✈️',
    description: 'Immigration, transport cards and directions.',
    openingLine: { korean: '방문 목적이 어떻게 되세요?', english: 'What is the purpose of your visit?', romanization: 'bangmun mokjeogi eotteoke doeseyo?' },
    isPremium: true,
  },
  {
    id: 'friends',
    title: 'Friends',
    emoji: '💬',
    description: 'Casual small talk and making plans.',
    openingLine: { korean: '오늘 뭐 해? 시간 있어?', english: 'What are you up to today? Free?', romanization: 'oneul mwo hae? sigan isseo?' },
    isPremium: true,
  },
  {
    id: 'dating',
    title: 'Dating',
    emoji: '💕',
    description: 'Ask someone out and keep it light.',
    openingLine: { korean: '주말에 뭐 했어요?', english: 'What did you do on the weekend?', romanization: 'jumare mwo haesseoyo?' },
    isPremium: true,
  },
  {
    id: 'work',
    title: 'Work',
    emoji: '💼',
    description: 'Meetings, schedules and polite requests.',
    openingLine: { korean: '안녕하세요. 회의 시간 확인 부탁드려요.', english: 'Hello. Could you confirm the meeting time?', romanization: 'annyeonghaseyo. hoeui sigan hwagin butakdeuryeoyo.' },
    isPremium: true,
  },
  {
    id: 'shopping',
    title: 'Shopping',
    emoji: '🛍️',
    description: 'Sizes, colours and asking for a discount.',
    openingLine: { korean: '찾으시는 거 있으세요?', english: 'Are you looking for something?', romanization: 'chajeusineun geo isseuseyo?' },
    isPremium: true,
  },
];
