import type { Vocabulary } from '@/types/content';

export const VOCABULARY: Vocabulary[] = [
  { id: 'v-annyeong', korean: '안녕하세요', english: 'Hello', romanization: 'annyeonghaseyo', exampleKorean: '안녕하세요, 저는 알렉스예요.', exampleEnglish: "Hello, I'm Alex.", audioUrl: null, category: 'greetings', level: 1 },
  { id: 'v-annyeonghi', korean: '안녕히 가세요', english: 'Goodbye (to someone leaving)', romanization: 'annyeonghi gaseyo', exampleKorean: '안녕히 가세요, 또 봐요!', exampleEnglish: 'Goodbye, see you again!', audioUrl: null, category: 'greetings', level: 1 },
  { id: 'v-annyeonghi-gyeseyo', korean: '안녕히 계세요', english: 'Goodbye (to someone staying)', romanization: 'annyeonghi gyeseyo', exampleKorean: '먼저 갈게요. 안녕히 계세요.', exampleEnglish: "I'll go first. Goodbye.", audioUrl: null, category: 'greetings', level: 1 },
  { id: 'v-ne', korean: '네', english: 'Yes', romanization: 'ne', exampleKorean: '네, 맞아요.', exampleEnglish: "Yes, that's right.", audioUrl: null, category: 'basics', level: 1 },
  { id: 'v-aniyo', korean: '아니요', english: 'No', romanization: 'aniyo', exampleKorean: '아니요, 괜찮아요.', exampleEnglish: "No, I'm fine.", audioUrl: null, category: 'basics', level: 1 },
  { id: 'v-gamsa', korean: '감사합니다', english: 'Thank you', romanization: 'gamsahamnida', exampleKorean: '도와줘서 감사합니다.', exampleEnglish: 'Thank you for helping me.', audioUrl: null, category: 'greetings', level: 1 },
  { id: 'v-gomawo', korean: '고마워요', english: 'Thanks (casual polite)', romanization: 'gomawoyo', exampleKorean: '정말 고마워요.', exampleEnglish: 'Thanks a lot.', audioUrl: null, category: 'greetings', level: 1 },
  { id: 'v-cheonmaneyo', korean: '천만에요', english: "You're welcome", romanization: 'cheonmaneyo', exampleKorean: '천만에요. 언제든지요.', exampleEnglish: "You're welcome. Any time.", audioUrl: null, category: 'greetings', level: 1 },
  { id: 'v-joesonghamnida', korean: '죄송합니다', english: 'I am sorry', romanization: 'joesonghamnida', exampleKorean: '늦어서 죄송합니다.', exampleEnglish: "I'm sorry for being late.", audioUrl: null, category: 'greetings', level: 1 },
  { id: 'v-jeogiyo', korean: '저기요', english: 'Excuse me', romanization: 'jeogiyo', exampleKorean: '저기요, 여기 물 주세요.', exampleEnglish: 'Excuse me, water please.', audioUrl: null, category: 'basics', level: 1 },
  { id: 'v-jeoneun', korean: '저는', english: 'I / I am', romanization: 'jeoneun', exampleKorean: '저는 학생이에요.', exampleEnglish: 'I am a student.', audioUrl: null, category: 'basics', level: 1 },
  { id: 'v-ireum', korean: '이름', english: 'Name', romanization: 'ireum', exampleKorean: '이름이 뭐예요?', exampleEnglish: 'What is your name?', audioUrl: null, category: 'basics', level: 1 },
  { id: 'v-nara', korean: '나라', english: 'Country', romanization: 'nara', exampleKorean: '어느 나라에서 왔어요?', exampleEnglish: 'Which country are you from?', audioUrl: null, category: 'basics', level: 1 },
  { id: 'v-migug', korean: '미국', english: 'The United States', romanization: 'miguk', exampleKorean: '저는 미국에서 왔어요.', exampleEnglish: 'I came from the United States.', audioUrl: null, category: 'basics', level: 1 },
  { id: 'v-mannaseo', korean: '반가워요', english: 'Nice to meet you', romanization: 'bangawoyo', exampleKorean: '만나서 반가워요.', exampleEnglish: 'Nice to meet you.', audioUrl: null, category: 'greetings', level: 1 },

  { id: 'v-keopi', korean: '커피', english: 'Coffee', romanization: 'keopi', exampleKorean: '커피 한 잔 주세요.', exampleEnglish: 'One coffee, please.', audioUrl: null, category: 'cafe', level: 1 },
  { id: 'v-amerikano', korean: '아메리카노', english: 'Americano', romanization: 'amerikano', exampleKorean: '아이스 아메리카노 주세요.', exampleEnglish: 'An iced americano, please.', audioUrl: null, category: 'cafe', level: 1 },
  { id: 'v-mul', korean: '물', english: 'Water', romanization: 'mul', exampleKorean: '물 좀 주세요.', exampleEnglish: 'Some water, please.', audioUrl: null, category: 'cafe', level: 1 },
  { id: 'v-juseyo', korean: '주세요', english: 'Please give me', romanization: 'juseyo', exampleKorean: '이거 주세요.', exampleEnglish: 'This one, please.', audioUrl: null, category: 'cafe', level: 1 },
  { id: 'v-hanjan', korean: '한 잔', english: 'One cup / glass', romanization: 'han jan', exampleKorean: '아메리카노 한 잔 주세요.', exampleEnglish: 'One americano, please.', audioUrl: null, category: 'cafe', level: 1 },
  { id: 'v-ttatteuthan', korean: '따뜻한', english: 'Hot (warm)', romanization: 'ttatteutan', exampleKorean: '따뜻한 라떼 주세요.', exampleEnglish: 'A hot latte, please.', audioUrl: null, category: 'cafe', level: 1 },
  { id: 'v-aiseu', korean: '아이스', english: 'Iced', romanization: 'aiseu', exampleKorean: '아이스로 주세요.', exampleEnglish: 'Iced, please.', audioUrl: null, category: 'cafe', level: 1 },
  { id: 'v-teigaut', korean: '테이크아웃', english: 'Takeout', romanization: 'teikeuaut', exampleKorean: '테이크아웃 할게요.', exampleEnglish: "I'll take it to go.", audioUrl: null, category: 'cafe', level: 1 },
  { id: 'v-eolmayeyo', korean: '얼마예요?', english: 'How much is it?', romanization: 'eolmayeyo?', exampleKorean: '이거 얼마예요?', exampleEnglish: 'How much is this?', audioUrl: null, category: 'shopping', level: 1 },
  { id: 'v-kadeu', korean: '카드', english: 'Card', romanization: 'kadeu', exampleKorean: '카드로 계산할게요.', exampleEnglish: "I'll pay by card.", audioUrl: null, category: 'shopping', level: 1 },
  { id: 'v-hyeongeum', korean: '현금', english: 'Cash', romanization: 'hyeongeum', exampleKorean: '현금으로 낼게요.', exampleEnglish: "I'll pay in cash.", audioUrl: null, category: 'shopping', level: 1 },
  { id: 'v-yeongsujeung', korean: '영수증', english: 'Receipt', romanization: 'yeongsujeung', exampleKorean: '영수증 주세요.', exampleEnglish: 'Receipt, please.', audioUrl: null, category: 'shopping', level: 1 },
  { id: 'v-bongtu', korean: '봉투', english: 'Bag', romanization: 'bongtu', exampleKorean: '봉투 필요하세요?', exampleEnglish: 'Do you need a bag?', audioUrl: null, category: 'shopping', level: 2 },
  { id: 'v-halin', korean: '할인', english: 'Discount', romanization: 'harin', exampleKorean: '할인 되나요?', exampleEnglish: 'Is there a discount?', audioUrl: null, category: 'shopping', level: 2 },
  { id: 'v-jogeum', korean: '조금', english: 'A little', romanization: 'jogeum', exampleKorean: '조금만 주세요.', exampleEnglish: 'Just a little, please.', audioUrl: null, category: 'basics', level: 1 },

  { id: 'v-masisseoyo', korean: '맛있어요', english: 'Delicious', romanization: 'masisseoyo', exampleKorean: '이 음식 정말 맛있어요.', exampleEnglish: 'This food is really delicious.', audioUrl: null, category: 'food', level: 1 },
  { id: 'v-maewoyo', korean: '매워요', english: 'It is spicy', romanization: 'maewoyo', exampleKorean: '이거 많이 매워요?', exampleEnglish: 'Is this very spicy?', audioUrl: null, category: 'food', level: 1 },
  { id: 'v-bap', korean: '밥', english: 'Rice / meal', romanization: 'bap', exampleKorean: '밥 먹었어요?', exampleEnglish: 'Have you eaten?', audioUrl: null, category: 'food', level: 1 },
  { id: 'v-kimchi', korean: '김치', english: 'Kimchi', romanization: 'gimchi', exampleKorean: '김치 더 주세요.', exampleEnglish: 'More kimchi, please.', audioUrl: null, category: 'food', level: 1 },
  { id: 'v-gogi', korean: '고기', english: 'Meat', romanization: 'gogi', exampleKorean: '고기 이인분 주세요.', exampleEnglish: 'Two servings of meat, please.', audioUrl: null, category: 'food', level: 2 },
  { id: 'v-menyu', korean: '메뉴', english: 'Menu', romanization: 'menyu', exampleKorean: '메뉴판 좀 주세요.', exampleEnglish: 'Could I get a menu?', audioUrl: null, category: 'food', level: 1 },
  { id: 'v-jumun', korean: '주문', english: 'Order', romanization: 'jumun', exampleKorean: '주문하시겠어요?', exampleEnglish: 'Would you like to order?', audioUrl: null, category: 'food', level: 2 },
  { id: 'v-pojang', korean: '포장', english: 'To pack / to go', romanization: 'pojang', exampleKorean: '포장해 주세요.', exampleEnglish: 'Please pack it to go.', audioUrl: null, category: 'food', level: 2 },
  { id: 'v-baedal', korean: '배달', english: 'Delivery', romanization: 'baedal', exampleKorean: '배달 되나요?', exampleEnglish: 'Do you deliver?', audioUrl: null, category: 'food', level: 2 },
  { id: 'v-pyeonuijeom', korean: '편의점', english: 'Convenience store', romanization: 'pyeonuijeom', exampleKorean: '편의점에 갈게요.', exampleEnglish: "I'll go to the convenience store.", audioUrl: null, category: 'daily', level: 1 },

  { id: 'v-jihacheol', korean: '지하철', english: 'Subway', romanization: 'jihacheol', exampleKorean: '지하철로 가요.', exampleEnglish: "Let's go by subway.", audioUrl: null, category: 'transport', level: 1 },
  { id: 'v-beoseu', korean: '버스', english: 'Bus', romanization: 'beoseu', exampleKorean: '버스 정류장이 어디예요?', exampleEnglish: 'Where is the bus stop?', audioUrl: null, category: 'transport', level: 1 },
  { id: 'v-taeksi', korean: '택시', english: 'Taxi', romanization: 'taeksi', exampleKorean: '택시 불러 주세요.', exampleEnglish: 'Please call a taxi.', audioUrl: null, category: 'transport', level: 1 },
  { id: 'v-yeok', korean: '역', english: 'Station', romanization: 'yeok', exampleKorean: '강남역으로 가 주세요.', exampleEnglish: 'To Gangnam Station, please.', audioUrl: null, category: 'transport', level: 1 },
  { id: 'v-eodiyeyo', korean: '어디예요?', english: 'Where is it?', romanization: 'eodiyeyo?', exampleKorean: '화장실이 어디예요?', exampleEnglish: 'Where is the bathroom?', audioUrl: null, category: 'transport', level: 1 },
  { id: 'v-yeogiyo-stop', korean: '여기서 세워 주세요', english: 'Please stop here', romanization: 'yeogiseo sewo juseyo', exampleKorean: '기사님, 여기서 세워 주세요.', exampleEnglish: 'Driver, please stop here.', audioUrl: null, category: 'transport', level: 2 },
  { id: 'v-hwanseung', korean: '환승', english: 'Transfer', romanization: 'hwanseung', exampleKorean: '어디서 환승해요?', exampleEnglish: 'Where do I transfer?', audioUrl: null, category: 'transport', level: 2 },
  { id: 'v-chulgu', korean: '출구', english: 'Exit', romanization: 'chulgu', exampleKorean: '삼 번 출구에서 만나요.', exampleEnglish: "Let's meet at exit 3.", audioUrl: null, category: 'transport', level: 2 },

  { id: 'v-oneul', korean: '오늘', english: 'Today', romanization: 'oneul', exampleKorean: '오늘 뭐 해요?', exampleEnglish: 'What are you doing today?', audioUrl: null, category: 'daily', level: 1 },
  { id: 'v-naeil', korean: '내일', english: 'Tomorrow', romanization: 'naeil', exampleKorean: '내일 만나요.', exampleEnglish: "Let's meet tomorrow.", audioUrl: null, category: 'daily', level: 1 },
  { id: 'v-jigeum', korean: '지금', english: 'Now', romanization: 'jigeum', exampleKorean: '지금 어디예요?', exampleEnglish: 'Where are you now?', audioUrl: null, category: 'daily', level: 1 },
  { id: 'v-joayo', korean: '좋아요', english: 'Good / I like it', romanization: 'joayo', exampleKorean: '이 카페 좋아요.', exampleEnglish: 'I like this cafe.', audioUrl: null, category: 'daily', level: 1 },
  { id: 'v-gwaenchanayo', korean: '괜찮아요', english: "It's okay / I'm fine", romanization: 'gwaenchanayo', exampleKorean: '괜찮아요, 걱정하지 마세요.', exampleEnglish: "It's okay, don't worry.", audioUrl: null, category: 'daily', level: 1 },
  { id: 'v-jaemiisseoyo', korean: '재미있어요', english: 'It is fun', romanization: 'jaemiisseoyo', exampleKorean: '한국어 공부 재미있어요.', exampleEnglish: 'Studying Korean is fun.', audioUrl: null, category: 'daily', level: 1 },
  { id: 'v-himdeureoyo', korean: '힘들어요', english: 'It is tough', romanization: 'himdeureoyo', exampleKorean: '오늘 좀 힘들어요.', exampleEnglish: "Today is a bit tough.", audioUrl: null, category: 'daily', level: 2 },
  { id: 'v-bappayo', korean: '바빠요', english: 'I am busy', romanization: 'bappayo', exampleKorean: '요즘 너무 바빠요.', exampleEnglish: "I'm so busy these days.", audioUrl: null, category: 'daily', level: 2 },
  { id: 'v-molla', korean: '몰라요', english: "I don't know", romanization: 'mollayo', exampleKorean: '잘 몰라요.', exampleEnglish: "I don't really know.", audioUrl: null, category: 'daily', level: 1 },
  { id: 'v-alayo', korean: '알아요', english: 'I know', romanization: 'arayo', exampleKorean: '그거 알아요!', exampleEnglish: 'I know that!', audioUrl: null, category: 'daily', level: 1 },

  { id: 'v-cheoncheonhi', korean: '천천히', english: 'Slowly', romanization: 'cheoncheonhi', exampleKorean: '천천히 말해 주세요.', exampleEnglish: 'Please speak slowly.', audioUrl: null, category: 'basics', level: 1 },
  { id: 'v-dasi', korean: '다시', english: 'Again', romanization: 'dasi', exampleKorean: '다시 한번 말해 주세요.', exampleEnglish: 'Please say it one more time.', audioUrl: null, category: 'basics', level: 1 },
  { id: 'v-hangugeo', korean: '한국어', english: 'Korean language', romanization: 'hangugeo', exampleKorean: '한국어를 배우고 있어요.', exampleEnglish: "I'm learning Korean.", audioUrl: null, category: 'basics', level: 1 },
  { id: 'v-yeongeo', korean: '영어', english: 'English', romanization: 'yeongeo', exampleKorean: '영어 할 수 있어요?', exampleEnglish: 'Can you speak English?', audioUrl: null, category: 'basics', level: 1 },
  { id: 'v-chingu', korean: '친구', english: 'Friend', romanization: 'chingu', exampleKorean: '친구랑 만나요.', exampleEnglish: "I'm meeting a friend.", audioUrl: null, category: 'daily', level: 1 },
  { id: 'v-hoesa', korean: '회사', english: 'Company / office', romanization: 'hoesa', exampleKorean: '회사에 가요.', exampleEnglish: "I'm going to the office.", audioUrl: null, category: 'work', level: 2 },
  { id: 'v-sugohasyeotseumnida', korean: '수고하셨습니다', english: 'Good work today', romanization: 'sugohasyeotseumnida', exampleKorean: '오늘도 수고하셨습니다.', exampleEnglish: 'Good work again today.', audioUrl: null, category: 'work', level: 3 },
  { id: 'v-hoeui', korean: '회의', english: 'Meeting', romanization: 'hoeui', exampleKorean: '회의가 세 시에 있어요.', exampleEnglish: 'The meeting is at 3.', audioUrl: null, category: 'work', level: 3 },

  { id: 'v-saenggak', korean: '생각', english: 'Thought / opinion', romanization: 'saenggak', exampleKorean: '제 생각에는 좋아요.', exampleEnglish: 'In my opinion, it is good.', audioUrl: null, category: 'conversation', level: 3 },
  { id: 'v-machayo', korean: '맞아요', english: "That's right", romanization: 'majayo', exampleKorean: '네, 맞아요.', exampleEnglish: "Yes, that's right.", audioUrl: null, category: 'conversation', level: 2 },
  { id: 'v-geulsseyo', korean: '글쎄요', english: 'Hmm, I am not sure', romanization: 'geulsseyo', exampleKorean: '글쎄요, 조금 어려워요.', exampleEnglish: "Hmm, it's a bit difficult.", audioUrl: null, category: 'conversation', level: 3 },
  { id: 'v-pigonhaeyo', korean: '피곤해요', english: 'I am tired', romanization: 'pigonhaeyo', exampleKorean: '오늘 너무 피곤해요.', exampleEnglish: "I'm so tired today.", audioUrl: null, category: 'feelings', level: 2 },
  { id: 'v-sinnayo', korean: '신나요', english: 'I am excited', romanization: 'sinnayo', exampleKorean: '내일 여행 가서 신나요.', exampleEnglish: "I'm excited to travel tomorrow.", audioUrl: null, category: 'feelings', level: 2 },
  { id: 'v-seuteureseu', korean: '스트레스', english: 'Stress', romanization: 'seuteureseu', exampleKorean: '스트레스 받았어요.', exampleEnglish: 'I got stressed out.', audioUrl: null, category: 'feelings', level: 3 },
  { id: 'v-seopseophaeyo', korean: '섭섭해요', english: 'I feel let down', romanization: 'seopseophaeyo', exampleKorean: '조금 섭섭했어요.', exampleEnglish: 'I felt a little let down.', audioUrl: null, category: 'feelings', level: 4 },
  { id: 'v-yaksok', korean: '약속', english: 'Plan / appointment', romanization: 'yaksok', exampleKorean: '오늘 약속 있어요.', exampleEnglish: 'I have plans today.', audioUrl: null, category: 'conversation', level: 2 },
  { id: 'v-eonje', korean: '언제', english: 'When', romanization: 'eonje', exampleKorean: '언제 만날까요?', exampleEnglish: 'When shall we meet?', audioUrl: null, category: 'conversation', level: 2 },
  { id: 'v-daeum-e', korean: '다음에', english: 'Next time', romanization: 'daeume', exampleKorean: '다음에 꼭 만나요.', exampleEnglish: "Let's definitely meet next time.", audioUrl: null, category: 'conversation', level: 2 },
  { id: 'v-mianhajiman', korean: '미안하지만', english: 'Sorry, but…', romanization: 'mianhajiman', exampleKorean: '미안하지만 오늘은 어려워요.', exampleEnglish: "Sorry, but today is difficult.", audioUrl: null, category: 'conversation', level: 3 },
  { id: 'v-yakguk', korean: '약국', english: 'Pharmacy', romanization: 'yakguk', exampleKorean: '약국이 어디예요?', exampleEnglish: 'Where is the pharmacy?', audioUrl: null, category: 'health', level: 2 },
  { id: 'v-yak', korean: '약', english: 'Medicine', romanization: 'yak', exampleKorean: '감기약 주세요.', exampleEnglish: 'Cold medicine, please.', audioUrl: null, category: 'health', level: 2 },
  { id: 'v-apayo', korean: '아파요', english: 'It hurts', romanization: 'apayo', exampleKorean: '머리가 아파요.', exampleEnglish: 'My head hurts.', audioUrl: null, category: 'health', level: 2 },
  { id: 'v-byeongwon', korean: '병원', english: 'Hospital / clinic', romanization: 'byeongwon', exampleKorean: '병원에 가야 해요.', exampleEnglish: 'I need to go to the clinic.', audioUrl: null, category: 'health', level: 2 },
  { id: 'v-dowajuseyo', korean: '도와주세요', english: 'Please help me', romanization: 'dowajuseyo', exampleKorean: '저기요, 도와주세요!', exampleEnglish: 'Excuse me, please help!', audioUrl: null, category: 'health', level: 1 },
  { id: 'v-gamgi', korean: '감기', english: 'A cold', romanization: 'gamgi', exampleKorean: '감기에 걸렸어요.', exampleEnglish: 'I caught a cold.', audioUrl: null, category: 'health', level: 2 },
  { id: 'v-jibju-in', korean: '집주인', english: 'Landlord', romanization: 'jipjuin', exampleKorean: '집주인한테 연락했어요.', exampleEnglish: 'I contacted the landlord.', audioUrl: null, category: 'living', level: 3 },
  { id: 'v-gowajang', korean: '고장났어요', english: 'It is broken', romanization: 'gojangnasseoyo', exampleKorean: '보일러가 고장났어요.', exampleEnglish: 'The boiler is broken.', audioUrl: null, category: 'living', level: 3 },
  { id: 'v-ttatteutan-mul', korean: '뜨거운 물', english: 'Hot water', romanization: 'tteugeoun mul', exampleKorean: '뜨거운 물이 안 나와요.', exampleEnglish: 'There is no hot water.', audioUrl: null, category: 'living', level: 3 },
  { id: 'v-gwanribi', korean: '관리비', english: 'Maintenance fee', romanization: 'gwallibi', exampleKorean: '관리비는 얼마예요?', exampleEnglish: 'How much is the maintenance fee?', audioUrl: null, category: 'living', level: 3 },
  { id: 'v-yeyak', korean: '예약', english: 'Reservation', romanization: 'yeyak', exampleKorean: '예약했어요.', exampleEnglish: 'I have a reservation.', audioUrl: null, category: 'travel', level: 2 },
  { id: 'v-chekeuin', korean: '체크인', english: 'Check-in', romanization: 'chekeuin', exampleKorean: '체크인 부탁드려요.', exampleEnglish: 'Check-in, please.', audioUrl: null, category: 'travel', level: 2 },
  { id: 'v-jim', korean: '짐', english: 'Luggage', romanization: 'jim', exampleKorean: '짐 맡길 수 있어요?', exampleEnglish: 'Can I leave my luggage?', audioUrl: null, category: 'travel', level: 2 },
  { id: 'v-ipjangnyo', korean: '입장료', english: 'Entry fee', romanization: 'ipjangnyo', exampleKorean: '입장료가 얼마예요?', exampleEnglish: 'How much is the entry fee?', audioUrl: null, category: 'travel', level: 3 },
  { id: 'v-sajin', korean: '사진', english: 'Photo', romanization: 'sajin', exampleKorean: '사진 찍어 주실 수 있어요?', exampleEnglish: 'Could you take a photo?', audioUrl: null, category: 'travel', level: 2 },
  { id: 'v-butakdeurimnida', korean: '부탁드립니다', english: 'I kindly ask you', romanization: 'butakdeurimnida', exampleKorean: '확인 부탁드립니다.', exampleEnglish: 'Please kindly confirm.', audioUrl: null, category: 'work', level: 4 },
  { id: 'v-hwagin', korean: '확인', english: 'Confirmation / check', romanization: 'hwagin', exampleKorean: '확인했습니다.', exampleEnglish: 'I have confirmed it.', audioUrl: null, category: 'work', level: 3 },
  { id: 'v-jeonhandeurimnida', korean: '전달드립니다', english: 'I am forwarding this', romanization: 'jeondaldeurimnida', exampleKorean: '자료 전달드립니다.', exampleEnglish: 'I am forwarding the materials.', audioUrl: null, category: 'work', level: 4 },
  { id: 'v-ilcheong', korean: '일정', english: 'Schedule', romanization: 'iljeong', exampleKorean: '일정 조정 가능할까요?', exampleEnglish: 'Could we adjust the schedule?', audioUrl: null, category: 'work', level: 4 },
  { id: 'v-chagaun', korean: '차가운', english: 'iced / cold', romanization: 'chagaun', exampleKorean: '차가운 아메리카노로 주세요.', exampleEnglish: 'An iced americano, please.', audioUrl: null, category: 'cafe', level: 1 },
  { id: 'v-meogeoyo', korean: '먹어요', english: 'to eat', romanization: 'meogeoyo', exampleKorean: '여기서 먹고 갈게요.', exampleEnglish: "I'll eat in.", audioUrl: null, category: 'cafe', level: 1 },
  { id: 'v-eolmaeyo', korean: '얼마예요', english: 'how much is it', romanization: 'eolmayeyo', exampleKorean: '이거 얼마예요?', exampleEnglish: 'How much is this?', audioUrl: null, category: 'shopping', level: 1 },
  { id: 'v-maepda', korean: '맵다', english: 'to be spicy', romanization: 'maepda', exampleKorean: '이거 많이 매워요?', exampleEnglish: 'Is this very spicy?', audioUrl: null, category: 'food', level: 2 },
  { id: 'v-masitda', korean: '맛있다', english: 'to be delicious', romanization: 'masitda', exampleKorean: '진짜 맛있어요!', exampleEnglish: "It's really delicious!", audioUrl: null, category: 'food', level: 1 },
  { id: 'v-banchan', korean: '반찬', english: 'side dishes', romanization: 'banchan', exampleKorean: '반찬 더 주세요.', exampleEnglish: 'More side dishes, please.', audioUrl: null, category: 'food', level: 2 },
  { id: 'v-sutgarak', korean: '숟가락', english: 'spoon', romanization: 'sutgarak', exampleKorean: '숟가락 하나 더 주세요.', exampleEnglish: 'One more spoon, please.', audioUrl: null, category: 'food', level: 1 },
  { id: 'v-jeotgarak', korean: '젓가락', english: 'chopsticks', romanization: 'jeotgarak', exampleKorean: '젓가락 어디 있어요?', exampleEnglish: 'Where are the chopsticks?', audioUrl: null, category: 'food', level: 1 },
  { id: 'v-gyesanseo', korean: '계산서', english: 'the bill', romanization: 'gyesanseo', exampleKorean: '계산서 주세요.', exampleEnglish: 'The bill, please.', audioUrl: null, category: 'food', level: 2 },
  { id: 'v-ttarottaro', korean: '따로따로', english: 'separately', romanization: 'ttarottaro', exampleKorean: '따로따로 계산할게요.', exampleEnglish: "We'll pay separately.", audioUrl: null, category: 'food', level: 2 },
  { id: 'v-jusikada', korean: '주시겠어요', english: 'could you give me', romanization: 'jusigesseoyo', exampleKorean: '영수증 주시겠어요?', exampleEnglish: 'Could I get the receipt?', audioUrl: null, category: 'shopping', level: 2 },
  { id: 'v-ripil', korean: '리필', english: 'refill', romanization: 'ripil', exampleKorean: '리필 되나요?', exampleEnglish: 'Can I get a refill?', audioUrl: null, category: 'cafe', level: 2 },
  { id: 'v-noseon', korean: '노선', english: 'line / route', romanization: 'noseon', exampleKorean: '2호선 타세요.', exampleEnglish: 'Take line 2.', audioUrl: null, category: 'transport', level: 2 },
  { id: 'v-taxi-japda', korean: '택시 잡다', english: 'to catch a taxi', romanization: 'taeksi japda', exampleKorean: '택시 잡을까요?', exampleEnglish: 'Shall we catch a taxi?', audioUrl: null, category: 'transport', level: 2 },
  { id: 'v-sewojuseyo', korean: '세워 주세요', english: 'please stop', romanization: 'sewo juseyo', exampleKorean: '여기서 세워 주세요.', exampleEnglish: 'Please stop here.', audioUrl: null, category: 'transport', level: 2 },
  { id: 'v-eolmana', korean: '얼마나', english: 'how long / how much', romanization: 'eolmana', exampleKorean: '얼마나 걸려요?', exampleEnglish: 'How long does it take?', audioUrl: null, category: 'travel', level: 1 },
  { id: 'v-gillhhh', korean: '길', english: 'road / way', romanization: 'gil', exampleKorean: '길 좀 물어봐도 될까요?', exampleEnglish: 'Could I ask for directions?', audioUrl: null, category: 'travel', level: 1 },
  { id: 'v-jikjin', korean: '직진', english: 'go straight', romanization: 'jikjin', exampleKorean: '직진하세요.', exampleEnglish: 'Go straight.', audioUrl: null, category: 'travel', level: 2 },
  { id: 'v-oenjjok', korean: '왼쪽', english: 'left', romanization: 'oenjjok', exampleKorean: '왼쪽으로 가세요.', exampleEnglish: 'Go left.', audioUrl: null, category: 'travel', level: 1 },
  { id: 'v-oreunjjok', korean: '오른쪽', english: 'right', romanization: 'oreunjjok', exampleKorean: '오른쪽에 있어요.', exampleEnglish: "It's on the right.", audioUrl: null, category: 'travel', level: 1 },
  { id: 'v-yeogi', korean: '여기', english: 'here', romanization: 'yeogi', exampleKorean: '여기가 어디예요?', exampleEnglish: 'Where is this?', audioUrl: null, category: 'travel', level: 1 },
  { id: 'v-jeogi', korean: '저기', english: 'over there', romanization: 'jeogi', exampleKorean: '저기 보이는 건물이요.', exampleEnglish: 'That building over there.', audioUrl: null, category: 'travel', level: 1 },
  { id: 'v-naerida', korean: '내리다', english: 'to get off', romanization: 'naerida', exampleKorean: '여기서 내릴게요.', exampleEnglish: "I'll get off here.", audioUrl: null, category: 'transport', level: 2 },
  { id: 'v-tada', korean: '타다', english: 'to ride / get on', romanization: 'tada', exampleKorean: '버스 타고 가요.', exampleEnglish: "Let's go by bus.", audioUrl: null, category: 'transport', level: 1 },
  { id: 'v-gonghang', korean: '공항', english: 'airport', romanization: 'gonghang', exampleKorean: '공항까지 얼마예요?', exampleEnglish: 'How much to the airport?', audioUrl: null, category: 'travel', level: 2 },
  { id: 'v-yeogwon', korean: '여권', english: 'passport', romanization: 'yeogwon', exampleKorean: '여권 보여 주세요.', exampleEnglish: 'Please show your passport.', audioUrl: null, category: 'travel', level: 2 },
  { id: 'v-hoesik', korean: '회식', english: 'company dinner', romanization: 'hoesik', exampleKorean: '오늘 회식 있어요.', exampleEnglish: 'We have a team dinner today.', audioUrl: null, category: 'work', level: 3 },
  { id: 'v-yageun', korean: '야근', english: 'working late', romanization: 'yageun', exampleKorean: '오늘 야근이에요.', exampleEnglish: "I'm working late today.", audioUrl: null, category: 'work', level: 3 },
  { id: 'v-bogo', korean: '보고', english: 'report', romanization: 'bogo', exampleKorean: '보고서 보냈어요.', exampleEnglish: 'I sent the report.', audioUrl: null, category: 'work', level: 3 },
  { id: 'v-buttak', korean: '부탁', english: 'favour / request', romanization: 'butak', exampleKorean: '부탁 하나만 드려도 될까요?', exampleEnglish: 'Could I ask you a favour?', audioUrl: null, category: 'work', level: 3 },
  { id: 'v-majgamm', korean: '마감', english: 'deadline', romanization: 'magam', exampleKorean: '마감이 언제예요?', exampleEnglish: 'When is the deadline?', audioUrl: null, category: 'work', level: 3 },
  { id: 'v-hyuga', korean: '휴가', english: 'vacation / leave', romanization: 'hyuga', exampleKorean: '다음 주에 휴가예요.', exampleEnglish: "I'm on leave next week.", audioUrl: null, category: 'work', level: 3 },
  { id: 'v-teim', korean: '팀', english: 'team', romanization: 'tim', exampleKorean: '우리 팀이에요.', exampleEnglish: 'This is my team.', audioUrl: null, category: 'work', level: 2 },
  { id: 'v-daepyo', korean: '대표', english: 'CEO / representative', romanization: 'daepyo', exampleKorean: '대표님 계세요?', exampleEnglish: 'Is the CEO in?', audioUrl: null, category: 'work', level: 4 },
  { id: 'v-wolse', korean: '월세', english: 'monthly rent', romanization: 'wolse', exampleKorean: '월세가 얼마예요?', exampleEnglish: 'How much is the monthly rent?', audioUrl: null, category: 'living', level: 3 },
  { id: 'v-eunhaeng', korean: '은행', english: 'bank', romanization: 'eunhaeng', exampleKorean: '은행 몇 시에 열어요?', exampleEnglish: 'What time does the bank open?', audioUrl: null, category: 'living', level: 2 },
  { id: 'v-tongjang', korean: '통장', english: 'bank account', romanization: 'tongjang', exampleKorean: '통장 만들고 싶어요.', exampleEnglish: "I'd like to open an account.", audioUrl: null, category: 'living', level: 3 },
  { id: 'v-sseuregi', korean: '쓰레기', english: 'rubbish', romanization: 'sseuregi', exampleKorean: '쓰레기 버리고 올게요.', exampleEnglish: "I'll go take the rubbish out.", audioUrl: null, category: 'living', level: 2 },
  { id: 'v-bunri-baechul', korean: '분리수거', english: 'recycling separation', romanization: 'bullisugeo', exampleKorean: '분리수거 언제 해요?', exampleEnglish: 'When is the recycling day?', audioUrl: null, category: 'living', level: 3 },
  { id: 'v-taekbae', korean: '택배', english: 'parcel delivery', romanization: 'taekbae', exampleKorean: '택배 왔어요.', exampleEnglish: 'A parcel arrived.', audioUrl: null, category: 'living', level: 2 },
  { id: 'v-sireoyo', korean: '싫어요', english: "I don't like it", romanization: 'sireoyo', exampleKorean: '저는 매운 거 싫어요.', exampleEnglish: "I don't like spicy food.", audioUrl: null, category: 'feelings', level: 1 },
  { id: 'v-jaemiitda', korean: '재미있다', english: 'to be fun', romanization: 'jaemiitda', exampleKorean: '한국어 공부 재미있어요.', exampleEnglish: 'Studying Korean is fun.', audioUrl: null, category: 'feelings', level: 1 },
  { id: 'v-himdeulda', korean: '힘들다', english: 'to be hard / tough', romanization: 'himdeulda', exampleKorean: '요즘 좀 힘들어요.', exampleEnglish: 'Things are a bit tough lately.', audioUrl: null, category: 'feelings', level: 2 },
  { id: 'v-jinjja', korean: '진짜', english: 'really', romanization: 'jinjja', exampleKorean: '진짜요?', exampleEnglish: 'Really?', audioUrl: null, category: 'conversation', level: 1 },
  { id: 'v-geunyang', korean: '그냥', english: 'just / no particular reason', romanization: 'geunyang', exampleKorean: '그냥 물어봤어요.', exampleEnglish: 'I was just asking.', audioUrl: null, category: 'conversation', level: 2 },
  { id: 'v-hoksi', korean: '혹시', english: 'by any chance', romanization: 'hoksi', exampleKorean: '혹시 시간 있어요?', exampleEnglish: 'Do you have time, by any chance?', audioUrl: null, category: 'conversation', level: 2 },
  { id: 'v-amado', korean: '아마도', english: 'probably', romanization: 'amado', exampleKorean: '아마도 늦을 것 같아요.', exampleEnglish: "I'll probably be late.", audioUrl: null, category: 'conversation', level: 2 },
  { id: 'v-geuraeseo', korean: '그래서', english: 'so / therefore', romanization: 'geuraeseo', exampleKorean: '그래서 못 갔어요.', exampleEnglish: "So I couldn't go.", audioUrl: null, category: 'conversation', level: 2 },
  { id: 'v-geunde', korean: '근데', english: 'but / by the way', romanization: 'geunde', exampleKorean: '근데 이거 뭐예요?', exampleEnglish: 'But what is this?', audioUrl: null, category: 'conversation', level: 2 },
  { id: 'v-mworago', korean: '뭐라고요', english: 'what did you say', romanization: 'mworagoyo', exampleKorean: '네? 뭐라고요?', exampleEnglish: 'Sorry? What did you say?', audioUrl: null, category: 'conversation', level: 1 },
  { id: 'v-daebak', korean: '대박', english: 'awesome / no way', romanization: 'daebak', exampleKorean: '와, 대박!', exampleEnglish: 'Wow, amazing!', audioUrl: null, category: 'daily', level: 2 },
  { id: 'v-hwaiting', korean: '화이팅', english: 'you can do it', romanization: 'hwaiting', exampleKorean: '내일 시험 화이팅!', exampleEnglish: 'Good luck on the exam tomorrow!', audioUrl: null, category: 'daily', level: 1 },
  { id: 'v-kkuljaem', korean: '꿀잼', english: 'super fun', romanization: 'kkuljaem', exampleKorean: '그 드라마 완전 꿀잼이에요.', exampleEnglish: 'That drama is so much fun.', audioUrl: null, category: 'daily', level: 2 },
  { id: 'v-nojaem', korean: '노잼', english: 'boring', romanization: 'nojaem', exampleKorean: '이 영화 노잼이에요.', exampleEnglish: 'This film is boring.', audioUrl: null, category: 'daily', level: 2 },
  { id: 'v-simkung', korean: '심쿵', english: 'heart flutter', romanization: 'simkung', exampleKorean: '심쿵했어요.', exampleEnglish: 'My heart skipped a beat.', audioUrl: null, category: 'daily', level: 2 },
  { id: 'v-eoljjang', korean: '얼짱', english: 'good-looking person', romanization: 'eoljjang', exampleKorean: '저 사람 완전 얼짱이에요.', exampleEnglish: 'That person is really good-looking.', audioUrl: null, category: 'daily', level: 2 },
  { id: 'v-mukbang', korean: '먹방', english: 'eating show', romanization: 'meokbang', exampleKorean: '먹방 보면서 밥 먹어요.', exampleEnglish: 'I eat while watching mukbang.', audioUrl: null, category: 'daily', level: 2 },
  { id: 'v-honbap', korean: '혼밥', english: 'eating alone', romanization: 'honbap', exampleKorean: '오늘은 혼밥이에요.', exampleEnglish: "I'm eating alone today.", audioUrl: null, category: 'daily', level: 2 },
  { id: 'v-sonyeon', korean: '선배', english: 'senior (school/work)', romanization: 'seonbae', exampleKorean: '선배가 사 주셨어요.', exampleEnglish: 'My senior treated me.', audioUrl: null, category: 'culture', level: 2 },
  { id: 'v-hubae', korean: '후배', english: 'junior (school/work)', romanization: 'hubae', exampleKorean: '후배랑 같이 갔어요.', exampleEnglish: 'I went with my junior.', audioUrl: null, category: 'culture', level: 2 },
  { id: 'v-eodi', korean: '어디', english: 'where', romanization: 'eodi', exampleKorean: '화장실이 어디예요?', exampleEnglish: 'Where is the bathroom?', audioUrl: null, category: 'basics', level: 1 },
  { id: 'v-nugu', korean: '누구', english: 'who', romanization: 'nugu', exampleKorean: '저 사람 누구예요?', exampleEnglish: 'Who is that person?', audioUrl: null, category: 'basics', level: 1 },
  { id: 'v-wae', korean: '왜', english: 'why', romanization: 'wae', exampleKorean: '왜 그래요?', exampleEnglish: "What's wrong?", audioUrl: null, category: 'basics', level: 1 },
  { id: 'v-eotteoke', korean: '어떻게', english: 'how', romanization: 'eotteoke', exampleKorean: '어떻게 가요?', exampleEnglish: 'How do I get there?', audioUrl: null, category: 'basics', level: 1 },
  { id: 'v-myeot', korean: '몇', english: 'how many', romanization: 'myeot', exampleKorean: '몇 명이에요?', exampleEnglish: 'How many people?', audioUrl: null, category: 'basics', level: 1 },
  { id: 'v-jom', korean: '좀', english: 'a little / please', romanization: 'jom', exampleKorean: '물 좀 주세요.', exampleEnglish: 'Some water, please.', audioUrl: null, category: 'basics', level: 1 },
  { id: 'v-deo', korean: '더', english: 'more', romanization: 'deo', exampleKorean: '조금 더 주세요.', exampleEnglish: 'A little more, please.', audioUrl: null, category: 'basics', level: 1 },
  { id: 'v-hamkke', korean: '같이', english: 'together', romanization: 'gachi', exampleKorean: '같이 갈래요?', exampleEnglish: 'Want to go together?', audioUrl: null, category: 'basics', level: 1 },
  { id: 'v-eoje', korean: '어제', english: 'yesterday', romanization: 'eoje', exampleKorean: '어제 뭐 했어요?', exampleEnglish: 'What did you do yesterday?', audioUrl: null, category: 'basics', level: 1 },
];
