-- =============================================================================
-- KoreanGo seed data — GENERATED FILE, DO NOT EDIT BY HAND.
--
-- Regenerate with:  npm run seed:generate
-- Apply with:       supabase db reset   (or psql -f supabase/seed/seed.sql)
--
-- Every statement is idempotent, so re-running it is safe.
-- =============================================================================

insert into public.courses (id, title, description, level, order_index, is_premium, emoji, accent)
values
  ('course-starter', 'Korean Starter', 'Read Hangul and say your first real Korean sentences.', 1, 1, false, '🌱', '#6C63FF'),
  ('course-everyday', 'Everyday Korean', 'The Korean you actually use in a normal Seoul day.', 2, 2, false, '☕', '#FFB84D'),
  ('course-conversation', 'Korean Conversation', 'Keep a conversation going with friends and coworkers.', 3, 3, true, '💬', '#FF6B81'),
  ('course-living', 'Living in Korea', 'Banks, hospitals, delivery apps and apartment life.', 3, 4, true, '🏙️', '#22B573'),
  ('course-travel', 'Korean Travel', 'Airports, taxis, hotels and ordering like a local.', 2, 5, true, '✈️', '#3AA0FF'),
  ('course-work', 'Korean for Work', 'Emails, meetings and 존댓말 that sounds professional.', 4, 6, true, '💼', '#8A6BFF')
on conflict (id) do update set title = excluded.title, description = excluded.description, level = excluded.level, order_index = excluded.order_index, is_premium = excluded.is_premium, emoji = excluded.emoji, accent = excluded.accent;

insert into public.units (id, course_id, title, description, order_index)
values
  ('unit-starter-1', 'course-starter', 'Hello Korea', 'Greetings, thank you, and introducing yourself.', 1),
  ('unit-starter-2', 'course-starter', 'Cafe Korean', 'Order coffee and pay like you live here.', 2),
  ('unit-starter-3', 'course-starter', 'Hangul Basics', 'Read 한글 letter by letter.', 3),
  ('unit-starter-4', 'course-starter', 'Numbers', 'Count, tell prices and give your phone number.', 4),
  ('unit-everyday-1', 'course-everyday', 'Food & Delivery', 'Restaurants, 배달 apps and convenience stores.', 1),
  ('unit-everyday-2', 'course-everyday', 'Getting Around', 'Subway, buses and taxis in Seoul.', 2),
  ('unit-everyday-3', 'course-everyday', 'Shopping', 'Sizes, prices and asking for help.', 3),
  ('unit-conversation-1', 'course-conversation', 'Making Friends', 'Small talk that does not feel like a textbook.', 1),
  ('unit-living-1', 'course-living', 'Daily Errands', 'Banks, post offices and package pickup.', 1),
  ('unit-travel-1', 'course-travel', 'Arrival', 'Airport, transport cards and checking in.', 1),
  ('unit-work-1', 'course-work', 'Office Korean', 'Greeting colleagues and joining a meeting.', 1)
on conflict (id) do update set course_id = excluded.course_id, title = excluded.title, description = excluded.description, order_index = excluded.order_index;

insert into public.lessons (id, unit_id, title, description, lesson_type, estimated_minutes, order_index, is_premium)
values
  ('lesson-greetings-hello', 'unit-starter-1', 'Hello & Goodbye', 'The two phrases you will use every single day.', 'conversation', 5, 1, false),
  ('lesson-greetings-yesno', 'unit-starter-1', 'Yes & No', 'Agree, disagree and sound natural doing it.', 'vocabulary', 5, 2, false),
  ('lesson-greetings-thanks', 'unit-starter-1', 'Thank You', 'Say thanks and reply when someone thanks you.', 'conversation', 5, 3, false),
  ('lesson-greetings-intro', 'unit-starter-1', 'Introducing Yourself', 'Name, country and a friendly first impression.', 'conversation', 7, 4, false),
  ('lesson-cafe-coffee', 'unit-starter-2', 'Ordering Coffee', 'Order an americano without switching to English.', 'conversation', 5, 1, false),
  ('lesson-cafe-water', 'unit-starter-2', 'Asking for Water', 'Ask for water, napkins and a to-go cup.', 'vocabulary', 5, 2, false),
  ('lesson-cafe-paying', 'unit-starter-2', 'Paying', 'Card, cash and points — the whole counter script.', 'conversation', 6, 3, false),
  ('lesson-hangul-consonants', 'unit-starter-3', 'Hangul Consonants', 'The 14 basic consonants and how they sound.', 'hangul', 8, 1, false),
  ('lesson-hangul-vowels', 'unit-starter-3', 'Hangul Vowels', 'Ten vowels built from three simple strokes.', 'hangul', 8, 2, false),
  ('lesson-numbers-sino', 'unit-starter-4', 'Numbers for Money', 'Sino-Korean numbers for prices and dates.', 'vocabulary', 6, 1, false),
  ('lesson-numbers-native', 'unit-starter-4', 'Counting Things', 'Native Korean numbers for cups, people and hours.', 'vocabulary', 6, 2, false),
  ('lesson-food-restaurant', 'unit-everyday-1', 'At a Restaurant', 'Order for the table and ask for the check.', 'conversation', 7, 1, false),
  ('lesson-food-convenience', 'unit-everyday-1', 'Convenience Store', 'The 편의점 phrases nobody teaches you.', 'conversation', 6, 2, false),
  ('lesson-transport-subway', 'unit-everyday-2', 'Taking the Subway', 'Transfers, exits and asking which line.', 'conversation', 7, 1, false),
  ('lesson-transport-taxi', 'unit-everyday-2', 'Taking a Taxi', 'Give an address and ask to stop here.', 'conversation', 6, 2, true),
  ('lesson-shopping-sizes', 'unit-everyday-3', 'Sizes & Colors', 'Try it on and ask for another size.', 'vocabulary', 6, 1, true),
  ('lesson-conversation-smalltalk', 'unit-conversation-1', 'Small Talk', 'Weather, weekends and what you did yesterday.', 'conversation', 8, 1, true),
  ('lesson-living-delivery', 'unit-living-1', 'Package Delivery', 'Talk to the 택배 driver and the front desk.', 'conversation', 7, 1, true),
  ('lesson-travel-airport', 'unit-travel-1', 'At the Airport', 'Immigration, T-money and the airport bus.', 'conversation', 7, 1, true),
  ('lesson-work-greetings', 'unit-work-1', 'Office Greetings', '수고하셨습니다 and when to actually use it.', 'culture', 6, 1, true)
on conflict (id) do update set unit_id = excluded.unit_id, title = excluded.title, description = excluded.description, lesson_type = excluded.lesson_type, estimated_minutes = excluded.estimated_minutes, order_index = excluded.order_index, is_premium = excluded.is_premium;

insert into public.vocabulary (id, korean, english, romanization, example_korean, example_english, audio_url, category, level)
values
  ('v-annyeong', '안녕하세요', 'Hello', 'annyeonghaseyo', '안녕하세요, 저는 알렉스예요.', 'Hello, I''m Alex.', null, 'greetings', 1),
  ('v-annyeonghi', '안녕히 가세요', 'Goodbye (to someone leaving)', 'annyeonghi gaseyo', '안녕히 가세요, 또 봐요!', 'Goodbye, see you again!', null, 'greetings', 1),
  ('v-annyeonghi-gyeseyo', '안녕히 계세요', 'Goodbye (to someone staying)', 'annyeonghi gyeseyo', '먼저 갈게요. 안녕히 계세요.', 'I''ll go first. Goodbye.', null, 'greetings', 1),
  ('v-ne', '네', 'Yes', 'ne', '네, 맞아요.', 'Yes, that''s right.', null, 'basics', 1),
  ('v-aniyo', '아니요', 'No', 'aniyo', '아니요, 괜찮아요.', 'No, I''m fine.', null, 'basics', 1),
  ('v-gamsa', '감사합니다', 'Thank you', 'gamsahamnida', '도와줘서 감사합니다.', 'Thank you for helping me.', null, 'greetings', 1),
  ('v-gomawo', '고마워요', 'Thanks (casual polite)', 'gomawoyo', '정말 고마워요.', 'Thanks a lot.', null, 'greetings', 1),
  ('v-cheonmaneyo', '천만에요', 'You''re welcome', 'cheonmaneyo', '천만에요. 언제든지요.', 'You''re welcome. Any time.', null, 'greetings', 1),
  ('v-joesonghamnida', '죄송합니다', 'I am sorry', 'joesonghamnida', '늦어서 죄송합니다.', 'I''m sorry for being late.', null, 'greetings', 1),
  ('v-jeogiyo', '저기요', 'Excuse me', 'jeogiyo', '저기요, 여기 물 주세요.', 'Excuse me, water please.', null, 'basics', 1),
  ('v-jeoneun', '저는', 'I / I am', 'jeoneun', '저는 학생이에요.', 'I am a student.', null, 'basics', 1),
  ('v-ireum', '이름', 'Name', 'ireum', '이름이 뭐예요?', 'What is your name?', null, 'basics', 1),
  ('v-nara', '나라', 'Country', 'nara', '어느 나라에서 왔어요?', 'Which country are you from?', null, 'basics', 1),
  ('v-migug', '미국', 'The United States', 'miguk', '저는 미국에서 왔어요.', 'I came from the United States.', null, 'basics', 1),
  ('v-mannaseo', '반가워요', 'Nice to meet you', 'bangawoyo', '만나서 반가워요.', 'Nice to meet you.', null, 'greetings', 1),
  ('v-keopi', '커피', 'Coffee', 'keopi', '커피 한 잔 주세요.', 'One coffee, please.', null, 'cafe', 1),
  ('v-amerikano', '아메리카노', 'Americano', 'amerikano', '아이스 아메리카노 주세요.', 'An iced americano, please.', null, 'cafe', 1),
  ('v-mul', '물', 'Water', 'mul', '물 좀 주세요.', 'Some water, please.', null, 'cafe', 1),
  ('v-juseyo', '주세요', 'Please give me', 'juseyo', '이거 주세요.', 'This one, please.', null, 'cafe', 1),
  ('v-hanjan', '한 잔', 'One cup / glass', 'han jan', '아메리카노 한 잔 주세요.', 'One americano, please.', null, 'cafe', 1),
  ('v-ttatteuthan', '따뜻한', 'Hot (warm)', 'ttatteutan', '따뜻한 라떼 주세요.', 'A hot latte, please.', null, 'cafe', 1),
  ('v-aiseu', '아이스', 'Iced', 'aiseu', '아이스로 주세요.', 'Iced, please.', null, 'cafe', 1),
  ('v-teigaut', '테이크아웃', 'Takeout', 'teikeuaut', '테이크아웃 할게요.', 'I''ll take it to go.', null, 'cafe', 1),
  ('v-eolmayeyo', '얼마예요?', 'How much is it?', 'eolmayeyo?', '이거 얼마예요?', 'How much is this?', null, 'shopping', 1),
  ('v-kadeu', '카드', 'Card', 'kadeu', '카드로 계산할게요.', 'I''ll pay by card.', null, 'shopping', 1),
  ('v-hyeongeum', '현금', 'Cash', 'hyeongeum', '현금으로 낼게요.', 'I''ll pay in cash.', null, 'shopping', 1),
  ('v-yeongsujeung', '영수증', 'Receipt', 'yeongsujeung', '영수증 주세요.', 'Receipt, please.', null, 'shopping', 1),
  ('v-bongtu', '봉투', 'Bag', 'bongtu', '봉투 필요하세요?', 'Do you need a bag?', null, 'shopping', 2),
  ('v-halin', '할인', 'Discount', 'harin', '할인 되나요?', 'Is there a discount?', null, 'shopping', 2),
  ('v-jogeum', '조금', 'A little', 'jogeum', '조금만 주세요.', 'Just a little, please.', null, 'basics', 1),
  ('v-masisseoyo', '맛있어요', 'Delicious', 'masisseoyo', '이 음식 정말 맛있어요.', 'This food is really delicious.', null, 'food', 1),
  ('v-maewoyo', '매워요', 'It is spicy', 'maewoyo', '이거 많이 매워요?', 'Is this very spicy?', null, 'food', 1),
  ('v-bap', '밥', 'Rice / meal', 'bap', '밥 먹었어요?', 'Have you eaten?', null, 'food', 1),
  ('v-kimchi', '김치', 'Kimchi', 'gimchi', '김치 더 주세요.', 'More kimchi, please.', null, 'food', 1),
  ('v-gogi', '고기', 'Meat', 'gogi', '고기 이인분 주세요.', 'Two servings of meat, please.', null, 'food', 2),
  ('v-menyu', '메뉴', 'Menu', 'menyu', '메뉴판 좀 주세요.', 'Could I get a menu?', null, 'food', 1),
  ('v-jumun', '주문', 'Order', 'jumun', '주문하시겠어요?', 'Would you like to order?', null, 'food', 2),
  ('v-pojang', '포장', 'To pack / to go', 'pojang', '포장해 주세요.', 'Please pack it to go.', null, 'food', 2),
  ('v-baedal', '배달', 'Delivery', 'baedal', '배달 되나요?', 'Do you deliver?', null, 'food', 2),
  ('v-pyeonuijeom', '편의점', 'Convenience store', 'pyeonuijeom', '편의점에 갈게요.', 'I''ll go to the convenience store.', null, 'daily', 1),
  ('v-jihacheol', '지하철', 'Subway', 'jihacheol', '지하철로 가요.', 'Let''s go by subway.', null, 'transport', 1),
  ('v-beoseu', '버스', 'Bus', 'beoseu', '버스 정류장이 어디예요?', 'Where is the bus stop?', null, 'transport', 1),
  ('v-taeksi', '택시', 'Taxi', 'taeksi', '택시 불러 주세요.', 'Please call a taxi.', null, 'transport', 1),
  ('v-yeok', '역', 'Station', 'yeok', '강남역으로 가 주세요.', 'To Gangnam Station, please.', null, 'transport', 1),
  ('v-eodiyeyo', '어디예요?', 'Where is it?', 'eodiyeyo?', '화장실이 어디예요?', 'Where is the bathroom?', null, 'transport', 1),
  ('v-yeogiyo-stop', '여기서 세워 주세요', 'Please stop here', 'yeogiseo sewo juseyo', '기사님, 여기서 세워 주세요.', 'Driver, please stop here.', null, 'transport', 2),
  ('v-hwanseung', '환승', 'Transfer', 'hwanseung', '어디서 환승해요?', 'Where do I transfer?', null, 'transport', 2),
  ('v-chulgu', '출구', 'Exit', 'chulgu', '삼 번 출구에서 만나요.', 'Let''s meet at exit 3.', null, 'transport', 2),
  ('v-oneul', '오늘', 'Today', 'oneul', '오늘 뭐 해요?', 'What are you doing today?', null, 'daily', 1),
  ('v-naeil', '내일', 'Tomorrow', 'naeil', '내일 만나요.', 'Let''s meet tomorrow.', null, 'daily', 1),
  ('v-jigeum', '지금', 'Now', 'jigeum', '지금 어디예요?', 'Where are you now?', null, 'daily', 1),
  ('v-joayo', '좋아요', 'Good / I like it', 'joayo', '이 카페 좋아요.', 'I like this cafe.', null, 'daily', 1),
  ('v-gwaenchanayo', '괜찮아요', 'It''s okay / I''m fine', 'gwaenchanayo', '괜찮아요, 걱정하지 마세요.', 'It''s okay, don''t worry.', null, 'daily', 1),
  ('v-jaemiisseoyo', '재미있어요', 'It is fun', 'jaemiisseoyo', '한국어 공부 재미있어요.', 'Studying Korean is fun.', null, 'daily', 1),
  ('v-himdeureoyo', '힘들어요', 'It is tough', 'himdeureoyo', '오늘 좀 힘들어요.', 'Today is a bit tough.', null, 'daily', 2),
  ('v-bappayo', '바빠요', 'I am busy', 'bappayo', '요즘 너무 바빠요.', 'I''m so busy these days.', null, 'daily', 2),
  ('v-molla', '몰라요', 'I don''t know', 'mollayo', '잘 몰라요.', 'I don''t really know.', null, 'daily', 1),
  ('v-alayo', '알아요', 'I know', 'arayo', '그거 알아요!', 'I know that!', null, 'daily', 1),
  ('v-cheoncheonhi', '천천히', 'Slowly', 'cheoncheonhi', '천천히 말해 주세요.', 'Please speak slowly.', null, 'basics', 1),
  ('v-dasi', '다시', 'Again', 'dasi', '다시 한번 말해 주세요.', 'Please say it one more time.', null, 'basics', 1),
  ('v-hangugeo', '한국어', 'Korean language', 'hangugeo', '한국어를 배우고 있어요.', 'I''m learning Korean.', null, 'basics', 1),
  ('v-yeongeo', '영어', 'English', 'yeongeo', '영어 할 수 있어요?', 'Can you speak English?', null, 'basics', 1),
  ('v-chingu', '친구', 'Friend', 'chingu', '친구랑 만나요.', 'I''m meeting a friend.', null, 'daily', 1),
  ('v-hoesa', '회사', 'Company / office', 'hoesa', '회사에 가요.', 'I''m going to the office.', null, 'work', 2),
  ('v-sugohasyeotseumnida', '수고하셨습니다', 'Good work today', 'sugohasyeotseumnida', '오늘도 수고하셨습니다.', 'Good work again today.', null, 'work', 3),
  ('v-hoeui', '회의', 'Meeting', 'hoeui', '회의가 세 시에 있어요.', 'The meeting is at 3.', null, 'work', 3)
on conflict (id) do update set korean = excluded.korean, english = excluded.english, romanization = excluded.romanization, example_korean = excluded.example_korean, example_english = excluded.example_english, audio_url = excluded.audio_url, category = excluded.category, level = excluded.level;

insert into public.lesson_content (id, lesson_id, content_type, korean_text, english_text, romanization, audio_url, metadata, order_index)
values
  ('lesson-greetings-hello-introduction-0', 'lesson-greetings-hello', 'introduction', null, 'Korean has one greeting that works almost everywhere — morning, evening, shop or office. You will hear it a hundred times a day in Seoul.', null, null, '{"heading":"Hello & Goodbye"}'::jsonb, 0),
  ('lesson-greetings-hello-vocabulary-1', 'lesson-greetings-hello', 'vocabulary', null, null, null, null, '{"vocabularyId":"v-annyeong"}'::jsonb, 1),
  ('lesson-greetings-hello-vocabulary-2', 'lesson-greetings-hello', 'vocabulary', null, null, null, null, '{"vocabularyId":"v-annyeonghi"}'::jsonb, 2),
  ('lesson-greetings-hello-vocabulary-3', 'lesson-greetings-hello', 'vocabulary', null, null, null, null, '{"vocabularyId":"v-annyeonghi-gyeseyo"}'::jsonb, 3),
  ('lesson-greetings-hello-vocabulary-4', 'lesson-greetings-hello', 'vocabulary', null, null, null, null, '{"vocabularyId":"v-mannaseo"}'::jsonb, 4),
  ('lesson-greetings-hello-expression-5', 'lesson-greetings-hello', 'expression', '안녕하세요.', 'Hello.', 'annyeonghaseyo.', null, '{"note":"Polite and safe with anyone."}'::jsonb, 5),
  ('lesson-greetings-hello-expression-6', 'lesson-greetings-hello', 'expression', '만나서 반가워요.', 'Nice to meet you.', 'mannaseo bangawoyo.', null, null, 6),
  ('lesson-greetings-hello-expression-7', 'lesson-greetings-hello', 'expression', '안녕히 가세요.', 'Goodbye — to the person leaving.', 'annyeonghi gaseyo.', null, null, 7),
  ('lesson-greetings-hello-expression-8', 'lesson-greetings-hello', 'expression', '안녕히 계세요.', 'Goodbye — to the person staying.', 'annyeonghi gyeseyo.', null, null, 8),
  ('lesson-greetings-hello-listening-9', 'lesson-greetings-hello', 'listening', '안녕하세요! 오랜만이에요.', 'Hello! Long time no see.', 'annyeonghaseyo! oraenmanieyo.', null, null, 9),
  ('lesson-greetings-hello-speaking-10', 'lesson-greetings-hello', 'speaking', '안녕하세요. 만나서 반가워요.', 'Hello. Nice to meet you.', 'annyeonghaseyo. mannaseo bangawoyo.', null, null, 10),
  ('lesson-greetings-hello-summary-11', 'lesson-greetings-hello', 'summary', null, null, null, null, '{"points":["안녕하세요 works as hello at any time of day.","Leaving? The person staying says 안녕히 가세요.","Staying? You say 안녕히 계세요 to them."]}'::jsonb, 11),
  ('lesson-greetings-yesno-introduction-0', 'lesson-greetings-yesno', 'introduction', null, 'Korean 네 is closer to "I hear you" than a hard yes. You will use it constantly as a listening signal.', null, null, '{"heading":"Yes & No"}'::jsonb, 0),
  ('lesson-greetings-yesno-vocabulary-1', 'lesson-greetings-yesno', 'vocabulary', null, null, null, null, '{"vocabularyId":"v-ne"}'::jsonb, 1),
  ('lesson-greetings-yesno-vocabulary-2', 'lesson-greetings-yesno', 'vocabulary', null, null, null, null, '{"vocabularyId":"v-aniyo"}'::jsonb, 2),
  ('lesson-greetings-yesno-vocabulary-3', 'lesson-greetings-yesno', 'vocabulary', null, null, null, null, '{"vocabularyId":"v-gwaenchanayo"}'::jsonb, 3),
  ('lesson-greetings-yesno-vocabulary-4', 'lesson-greetings-yesno', 'vocabulary', null, null, null, null, '{"vocabularyId":"v-joayo"}'::jsonb, 4),
  ('lesson-greetings-yesno-expression-5', 'lesson-greetings-yesno', 'expression', '네, 맞아요.', 'Yes, that''s right.', 'ne, majayo.', null, null, 5),
  ('lesson-greetings-yesno-expression-6', 'lesson-greetings-yesno', 'expression', '아니요, 괜찮아요.', 'No, I''m fine.', 'aniyo, gwaenchanayo.', null, null, 6),
  ('lesson-greetings-yesno-expression-7', 'lesson-greetings-yesno', 'expression', '네, 좋아요.', 'Yes, sounds good.', 'ne, joayo.', null, null, 7),
  ('lesson-greetings-yesno-listening-8', 'lesson-greetings-yesno', 'listening', '봉투 필요하세요? — 아니요, 괜찮아요.', 'Do you need a bag? — No, I’m fine.', 'bongtu piryohaseyo? — aniyo, gwaenchanayo.', null, null, 8),
  ('lesson-greetings-yesno-speaking-9', 'lesson-greetings-yesno', 'speaking', '네, 괜찮아요.', 'Yes, it''s fine.', 'ne, gwaenchanayo.', null, null, 9),
  ('lesson-greetings-yesno-summary-10', 'lesson-greetings-yesno', 'summary', null, null, null, null, '{"points":["네 = yes / I follow you.","아니요 = no.","괜찮아요 politely declines anything."]}'::jsonb, 10),
  ('lesson-greetings-thanks-introduction-0', 'lesson-greetings-thanks', 'introduction', null, 'There are two thank-yous you need: one formal, one warm. Getting the difference right makes you sound thoughtful.', null, null, '{"heading":"Thank You"}'::jsonb, 0),
  ('lesson-greetings-thanks-vocabulary-1', 'lesson-greetings-thanks', 'vocabulary', null, null, null, null, '{"vocabularyId":"v-gamsa"}'::jsonb, 1),
  ('lesson-greetings-thanks-vocabulary-2', 'lesson-greetings-thanks', 'vocabulary', null, null, null, null, '{"vocabularyId":"v-gomawo"}'::jsonb, 2),
  ('lesson-greetings-thanks-vocabulary-3', 'lesson-greetings-thanks', 'vocabulary', null, null, null, null, '{"vocabularyId":"v-cheonmaneyo"}'::jsonb, 3),
  ('lesson-greetings-thanks-vocabulary-4', 'lesson-greetings-thanks', 'vocabulary', null, null, null, null, '{"vocabularyId":"v-joesonghamnida"}'::jsonb, 4),
  ('lesson-greetings-thanks-expression-5', 'lesson-greetings-thanks', 'expression', '감사합니다.', 'Thank you.', 'gamsahamnida.', null, '{"note":"Formal — staff, elders, work."}'::jsonb, 5),
  ('lesson-greetings-thanks-expression-6', 'lesson-greetings-thanks', 'expression', '고마워요.', 'Thanks.', 'gomawoyo.', null, '{"note":"Warm — friends, peers."}'::jsonb, 6),
  ('lesson-greetings-thanks-expression-7', 'lesson-greetings-thanks', 'expression', '천만에요.', 'You''re welcome.', 'cheonmaneyo.', null, null, 7),
  ('lesson-greetings-thanks-listening-8', 'lesson-greetings-thanks', 'listening', '도와주셔서 감사합니다.', 'Thank you for your help.', 'dowajusyeoseo gamsahamnida.', null, null, 8),
  ('lesson-greetings-thanks-speaking-9', 'lesson-greetings-thanks', 'speaking', '정말 감사합니다.', 'Thank you so much.', 'jeongmal gamsahamnida.', null, null, 9),
  ('lesson-greetings-thanks-summary-10', 'lesson-greetings-thanks', 'summary', null, null, null, null, '{"points":["감사합니다 is never wrong.","고마워요 is for people close to you.","죄송합니다 is sorry, not thanks."]}'::jsonb, 10),
  ('lesson-greetings-intro-introduction-0', 'lesson-greetings-intro', 'introduction', null, 'Three sentences and you can introduce yourself to anyone in Korea: name, country, and a friendly closer.', null, null, '{"heading":"Introducing Yourself"}'::jsonb, 0),
  ('lesson-greetings-intro-vocabulary-1', 'lesson-greetings-intro', 'vocabulary', null, null, null, null, '{"vocabularyId":"v-jeoneun"}'::jsonb, 1),
  ('lesson-greetings-intro-vocabulary-2', 'lesson-greetings-intro', 'vocabulary', null, null, null, null, '{"vocabularyId":"v-ireum"}'::jsonb, 2),
  ('lesson-greetings-intro-vocabulary-3', 'lesson-greetings-intro', 'vocabulary', null, null, null, null, '{"vocabularyId":"v-nara"}'::jsonb, 3),
  ('lesson-greetings-intro-vocabulary-4', 'lesson-greetings-intro', 'vocabulary', null, null, null, null, '{"vocabularyId":"v-migug"}'::jsonb, 4),
  ('lesson-greetings-intro-vocabulary-5', 'lesson-greetings-intro', 'vocabulary', null, null, null, null, '{"vocabularyId":"v-mannaseo"}'::jsonb, 5),
  ('lesson-greetings-intro-expression-6', 'lesson-greetings-intro', 'expression', '저는 알렉스예요.', 'I''m Alex.', 'jeoneun alekseuyeyo.', null, '{"note":"Swap in your own name."}'::jsonb, 6),
  ('lesson-greetings-intro-expression-7', 'lesson-greetings-intro', 'expression', '저는 미국에서 왔어요.', 'I came from the United States.', 'jeoneun migugeseo wasseoyo.', null, null, 7),
  ('lesson-greetings-intro-expression-8', 'lesson-greetings-intro', 'expression', '이름이 뭐예요?', 'What is your name?', 'ireumi mwoyeyo?', null, null, 8),
  ('lesson-greetings-intro-listening-9', 'lesson-greetings-intro', 'listening', '어느 나라에서 왔어요?', 'Which country are you from?', 'eoneu naraeseo wasseoyo?', null, null, 9),
  ('lesson-greetings-intro-speaking-10', 'lesson-greetings-intro', 'speaking', '안녕하세요. 저는 알렉스예요. 만나서 반가워요.', 'Hello. I''m Alex. Nice to meet you.', 'annyeonghaseyo. jeoneun alekseuyeyo. mannaseo bangawoyo.', null, null, 10),
  ('lesson-greetings-intro-summary-11', 'lesson-greetings-intro', 'summary', null, null, null, null, '{"points":["저는 + name + 예요/이에요 introduces you.","~에서 왔어요 means \"I came from ~\".","Finish with 반가워요 to sound friendly."]}'::jsonb, 11),
  ('lesson-cafe-coffee-introduction-0', 'lesson-cafe-coffee', 'introduction', null, 'Korean cafe ordering is a fixed script. Learn it once and every cafe in the country works the same way.', null, null, '{"heading":"Ordering Coffee"}'::jsonb, 0),
  ('lesson-cafe-coffee-vocabulary-1', 'lesson-cafe-coffee', 'vocabulary', null, null, null, null, '{"vocabularyId":"v-keopi"}'::jsonb, 1),
  ('lesson-cafe-coffee-vocabulary-2', 'lesson-cafe-coffee', 'vocabulary', null, null, null, null, '{"vocabularyId":"v-amerikano"}'::jsonb, 2),
  ('lesson-cafe-coffee-vocabulary-3', 'lesson-cafe-coffee', 'vocabulary', null, null, null, null, '{"vocabularyId":"v-juseyo"}'::jsonb, 3),
  ('lesson-cafe-coffee-vocabulary-4', 'lesson-cafe-coffee', 'vocabulary', null, null, null, null, '{"vocabularyId":"v-hanjan"}'::jsonb, 4),
  ('lesson-cafe-coffee-vocabulary-5', 'lesson-cafe-coffee', 'vocabulary', null, null, null, null, '{"vocabularyId":"v-aiseu"}'::jsonb, 5),
  ('lesson-cafe-coffee-vocabulary-6', 'lesson-cafe-coffee', 'vocabulary', null, null, null, null, '{"vocabularyId":"v-ttatteuthan"}'::jsonb, 6),
  ('lesson-cafe-coffee-vocabulary-7', 'lesson-cafe-coffee', 'vocabulary', null, null, null, null, '{"vocabularyId":"v-teigaut"}'::jsonb, 7),
  ('lesson-cafe-coffee-expression-8', 'lesson-cafe-coffee', 'expression', '아메리카노 한 잔 주세요.', 'One americano, please.', 'amerikano han jan juseyo.', null, null, 8),
  ('lesson-cafe-coffee-expression-9', 'lesson-cafe-coffee', 'expression', '아이스로 주세요.', 'Iced, please.', 'aiseuro juseyo.', null, null, 9),
  ('lesson-cafe-coffee-expression-10', 'lesson-cafe-coffee', 'expression', '테이크아웃 할게요.', 'I''ll take it to go.', 'teikeuaut halgeyo.', null, null, 10),
  ('lesson-cafe-coffee-listening-11', 'lesson-cafe-coffee', 'listening', '드시고 가세요, 아니면 테이크아웃이세요?', 'For here or to go?', 'deusigo gaseyo, animyeon teikeuautiseyo?', null, null, 11),
  ('lesson-cafe-coffee-speaking-12', 'lesson-cafe-coffee', 'speaking', '아이스 아메리카노 한 잔 주세요.', 'One iced americano, please.', 'aiseu amerikano han jan juseyo.', null, null, 12),
  ('lesson-cafe-coffee-summary-13', 'lesson-cafe-coffee', 'summary', null, null, null, null, '{"points":["Anything + 주세요 = \"please give me that\".","한 잔 counts cups.","아이스 / 따뜻한 goes before the drink."]}'::jsonb, 13),
  ('lesson-cafe-water-introduction-0', 'lesson-cafe-water', 'introduction', null, 'Water is usually self-serve in Korea, but 저기요 plus 주세요 gets you anything you need.', null, null, '{"heading":"Asking for Water"}'::jsonb, 0),
  ('lesson-cafe-water-vocabulary-1', 'lesson-cafe-water', 'vocabulary', null, null, null, null, '{"vocabularyId":"v-mul"}'::jsonb, 1),
  ('lesson-cafe-water-vocabulary-2', 'lesson-cafe-water', 'vocabulary', null, null, null, null, '{"vocabularyId":"v-jeogiyo"}'::jsonb, 2),
  ('lesson-cafe-water-vocabulary-3', 'lesson-cafe-water', 'vocabulary', null, null, null, null, '{"vocabularyId":"v-jogeum"}'::jsonb, 3),
  ('lesson-cafe-water-vocabulary-4', 'lesson-cafe-water', 'vocabulary', null, null, null, null, '{"vocabularyId":"v-juseyo"}'::jsonb, 4),
  ('lesson-cafe-water-expression-5', 'lesson-cafe-water', 'expression', '저기요, 물 좀 주세요.', 'Excuse me, some water please.', 'jeogiyo, mul jom juseyo.', null, null, 5),
  ('lesson-cafe-water-expression-6', 'lesson-cafe-water', 'expression', '얼음 주세요.', 'Ice, please.', 'eoreum juseyo.', null, null, 6),
  ('lesson-cafe-water-listening-7', 'lesson-cafe-water', 'listening', '물은 셀프예요.', 'Water is self-serve.', 'mureun selpeuyeyo.', null, null, 7),
  ('lesson-cafe-water-speaking-8', 'lesson-cafe-water', 'speaking', '저기요, 물 좀 주세요.', 'Excuse me, some water please.', 'jeogiyo, mul jom juseyo.', null, null, 8),
  ('lesson-cafe-water-summary-9', 'lesson-cafe-water', 'summary', null, null, null, null, '{"points":["저기요 is how you flag staff politely.","좀 softens a request.","셀프 means self-serve."]}'::jsonb, 9),
  ('lesson-cafe-paying-introduction-0', 'lesson-cafe-paying', 'introduction', null, 'Card is king in Korea. These four lines cover the entire counter exchange.', null, null, '{"heading":"Paying"}'::jsonb, 0),
  ('lesson-cafe-paying-vocabulary-1', 'lesson-cafe-paying', 'vocabulary', null, null, null, null, '{"vocabularyId":"v-eolmayeyo"}'::jsonb, 1),
  ('lesson-cafe-paying-vocabulary-2', 'lesson-cafe-paying', 'vocabulary', null, null, null, null, '{"vocabularyId":"v-kadeu"}'::jsonb, 2),
  ('lesson-cafe-paying-vocabulary-3', 'lesson-cafe-paying', 'vocabulary', null, null, null, null, '{"vocabularyId":"v-hyeongeum"}'::jsonb, 3),
  ('lesson-cafe-paying-vocabulary-4', 'lesson-cafe-paying', 'vocabulary', null, null, null, null, '{"vocabularyId":"v-yeongsujeung"}'::jsonb, 4),
  ('lesson-cafe-paying-expression-5', 'lesson-cafe-paying', 'expression', '얼마예요?', 'How much is it?', 'eolmayeyo?', null, null, 5),
  ('lesson-cafe-paying-expression-6', 'lesson-cafe-paying', 'expression', '카드로 할게요.', 'I''ll pay by card.', 'kadeuro halgeyo.', null, null, 6),
  ('lesson-cafe-paying-expression-7', 'lesson-cafe-paying', 'expression', '영수증 주세요.', 'Receipt, please.', 'yeongsujeung juseyo.', null, null, 7),
  ('lesson-cafe-paying-listening-8', 'lesson-cafe-paying', 'listening', '적립 카드 있으세요?', 'Do you have a points card?', 'jeongnip kadeu isseuseyo?', null, null, 8),
  ('lesson-cafe-paying-speaking-9', 'lesson-cafe-paying', 'speaking', '카드로 할게요. 영수증 주세요.', 'I''ll pay by card. Receipt, please.', 'kadeuro halgeyo. yeongsujeung juseyo.', null, null, 9),
  ('lesson-cafe-paying-summary-10', 'lesson-cafe-paying', 'summary', null, null, null, null, '{"points":["얼마예요? asks any price.","~로 할게요 chooses a payment method.","Staff will ask about 적립 (points) — 괜찮아요 is a fine answer."]}'::jsonb, 10),
  ('lesson-hangul-consonants-introduction-0', 'lesson-hangul-consonants', 'introduction', null, 'Hangul was designed to be learned in a day. Each consonant is a picture of the shape your mouth makes.', null, null, '{"heading":"Hangul Consonants"}'::jsonb, 0),
  ('lesson-hangul-consonants-vocabulary-1', 'lesson-hangul-consonants', 'vocabulary', null, null, null, null, '{"vocabularyId":"v-hangugeo"}'::jsonb, 1),
  ('lesson-hangul-consonants-expression-2', 'lesson-hangul-consonants', 'expression', 'ㄱ', 'g / k — back of the tongue rising', 'g/k', null, null, 2),
  ('lesson-hangul-consonants-expression-3', 'lesson-hangul-consonants', 'expression', 'ㄴ', 'n — tongue tip at the ridge', 'n', null, null, 3),
  ('lesson-hangul-consonants-expression-4', 'lesson-hangul-consonants', 'expression', 'ㅁ', 'm — closed mouth', 'm', null, null, 4),
  ('lesson-hangul-consonants-expression-5', 'lesson-hangul-consonants', 'expression', 'ㅅ', 's — air through a narrow gap', 's', null, null, 5),
  ('lesson-hangul-consonants-listening-6', 'lesson-hangul-consonants', 'listening', '가 나 마 사', 'ga na ma sa', 'ga na ma sa', null, null, 6),
  ('lesson-hangul-consonants-speaking-7', 'lesson-hangul-consonants', 'speaking', '가나다라마바사', 'The Korean alphabet song order.', 'ganadaramabasa', null, null, 7),
  ('lesson-hangul-consonants-summary-8', 'lesson-hangul-consonants', 'summary', null, null, null, null, '{"points":["Consonants are drawn from mouth shapes.","A syllable always starts with a consonant.","ㅇ at the start is silent."]}'::jsonb, 8),
  ('lesson-hangul-vowels-introduction-0', 'lesson-hangul-vowels', 'introduction', null, 'Every vowel is built from three strokes: a vertical line (person), a horizontal line (earth), and a dot (sky).', null, null, '{"heading":"Hangul Vowels"}'::jsonb, 0),
  ('lesson-hangul-vowels-vocabulary-1', 'lesson-hangul-vowels', 'vocabulary', null, null, null, null, '{"vocabularyId":"v-hangugeo"}'::jsonb, 1),
  ('lesson-hangul-vowels-expression-2', 'lesson-hangul-vowels', 'expression', 'ㅏ', 'a — as in "father"', 'a', null, null, 2),
  ('lesson-hangul-vowels-expression-3', 'lesson-hangul-vowels', 'expression', 'ㅓ', 'eo — as in "sun"', 'eo', null, null, 3),
  ('lesson-hangul-vowels-expression-4', 'lesson-hangul-vowels', 'expression', 'ㅗ', 'o — as in "go"', 'o', null, null, 4),
  ('lesson-hangul-vowels-expression-5', 'lesson-hangul-vowels', 'expression', 'ㅜ', 'u — as in "moon"', 'u', null, null, 5),
  ('lesson-hangul-vowels-listening-6', 'lesson-hangul-vowels', 'listening', '아 어 오 우 이', 'a eo o u i', 'a eo o u i', null, null, 6),
  ('lesson-hangul-vowels-speaking-7', 'lesson-hangul-vowels', 'speaking', '아 어 오 우 이', 'Practise the five core vowels.', 'a eo o u i', null, null, 7),
  ('lesson-hangul-vowels-summary-8', 'lesson-hangul-vowels', 'summary', null, null, null, null, '{"points":["Vertical vowels sit to the right of the consonant.","Horizontal vowels sit underneath.","Adding a stroke adds a \"y\" sound: ㅏ → ㅑ."]}'::jsonb, 8),
  ('lesson-numbers-sino-introduction-0', 'lesson-numbers-sino', 'introduction', null, 'Korean has two number systems. Sino-Korean is the one on every price tag and phone number.', null, null, '{"heading":"Numbers for Money"}'::jsonb, 0),
  ('lesson-numbers-sino-vocabulary-1', 'lesson-numbers-sino', 'vocabulary', null, null, null, null, '{"vocabularyId":"v-eolmayeyo"}'::jsonb, 1),
  ('lesson-numbers-sino-vocabulary-2', 'lesson-numbers-sino', 'vocabulary', null, null, null, null, '{"vocabularyId":"v-kadeu"}'::jsonb, 2),
  ('lesson-numbers-sino-expression-3', 'lesson-numbers-sino', 'expression', '일 이 삼 사 오', '1 2 3 4 5', 'il i sam sa o', null, null, 3),
  ('lesson-numbers-sino-expression-4', 'lesson-numbers-sino', 'expression', '육 칠 팔 구 십', '6 7 8 9 10', 'yuk chil pal gu sip', null, null, 4),
  ('lesson-numbers-sino-expression-5', 'lesson-numbers-sino', 'expression', '오천 원이에요.', 'It''s 5,000 won.', 'ocheon wonieyo.', null, null, 5),
  ('lesson-numbers-sino-listening-6', 'lesson-numbers-sino', 'listening', '사천오백 원입니다.', 'That''s 4,500 won.', 'sacheonobaek wonimnida.', null, null, 6),
  ('lesson-numbers-sino-speaking-7', 'lesson-numbers-sino', 'speaking', '이거 얼마예요?', 'How much is this?', 'igeo eolmayeyo?', null, null, 7),
  ('lesson-numbers-sino-summary-8', 'lesson-numbers-sino', 'summary', null, null, null, null, '{"points":["Sino numbers are used for money, dates and phone numbers.","천 = 1,000, 만 = 10,000.","Korean counts in units of 만, not thousands."]}'::jsonb, 8),
  ('lesson-numbers-native-introduction-0', 'lesson-numbers-native', 'introduction', null, 'Native Korean numbers count objects, people, cups and hours — the things you point at.', null, null, '{"heading":"Counting Things"}'::jsonb, 0),
  ('lesson-numbers-native-vocabulary-1', 'lesson-numbers-native', 'vocabulary', null, null, null, null, '{"vocabularyId":"v-hanjan"}'::jsonb, 1),
  ('lesson-numbers-native-vocabulary-2', 'lesson-numbers-native', 'vocabulary', null, null, null, null, '{"vocabularyId":"v-keopi"}'::jsonb, 2),
  ('lesson-numbers-native-expression-3', 'lesson-numbers-native', 'expression', '하나 둘 셋 넷 다섯', '1 2 3 4 5', 'hana dul set net daseot', null, null, 3),
  ('lesson-numbers-native-expression-4', 'lesson-numbers-native', 'expression', '커피 두 잔 주세요.', 'Two coffees, please.', 'keopi du jan juseyo.', null, null, 4),
  ('lesson-numbers-native-listening-5', 'lesson-numbers-native', 'listening', '몇 분이세요?', 'How many people?', 'myeot buniseyo?', null, null, 5),
  ('lesson-numbers-native-speaking-6', 'lesson-numbers-native', 'speaking', '두 명이에요.', 'Two people.', 'du myeongieyo.', null, null, 6),
  ('lesson-numbers-native-summary-7', 'lesson-numbers-native', 'summary', null, null, null, null, '{"points":["하나 becomes 한 before a counter: 한 잔.","잔 for cups, 명 for people, 개 for things.","Use native numbers up to 99."]}'::jsonb, 7),
  ('lesson-food-restaurant-introduction-0', 'lesson-food-restaurant', 'introduction', null, 'Ordering for a table in Korea is a team sport. These lines cover arriving, ordering and paying.', null, null, '{"heading":"At a Restaurant"}'::jsonb, 0),
  ('lesson-food-restaurant-vocabulary-1', 'lesson-food-restaurant', 'vocabulary', null, null, null, null, '{"vocabularyId":"v-menyu"}'::jsonb, 1),
  ('lesson-food-restaurant-vocabulary-2', 'lesson-food-restaurant', 'vocabulary', null, null, null, null, '{"vocabularyId":"v-jumun"}'::jsonb, 2),
  ('lesson-food-restaurant-vocabulary-3', 'lesson-food-restaurant', 'vocabulary', null, null, null, null, '{"vocabularyId":"v-gogi"}'::jsonb, 3),
  ('lesson-food-restaurant-vocabulary-4', 'lesson-food-restaurant', 'vocabulary', null, null, null, null, '{"vocabularyId":"v-masisseoyo"}'::jsonb, 4),
  ('lesson-food-restaurant-vocabulary-5', 'lesson-food-restaurant', 'vocabulary', null, null, null, null, '{"vocabularyId":"v-maewoyo"}'::jsonb, 5),
  ('lesson-food-restaurant-expression-6', 'lesson-food-restaurant', 'expression', '메뉴판 좀 주세요.', 'Could I get a menu?', 'menyupan jom juseyo.', null, null, 6),
  ('lesson-food-restaurant-expression-7', 'lesson-food-restaurant', 'expression', '이거 두 개 주세요.', 'Two of these, please.', 'igeo du gae juseyo.', null, null, 7),
  ('lesson-food-restaurant-expression-8', 'lesson-food-restaurant', 'expression', '계산할게요.', 'I''ll pay now.', 'gyesanhalgeyo.', null, null, 8),
  ('lesson-food-restaurant-listening-9', 'lesson-food-restaurant', 'listening', '주문하시겠어요?', 'Would you like to order?', 'jumunhasigesseoyo?', null, null, 9),
  ('lesson-food-restaurant-speaking-10', 'lesson-food-restaurant', 'speaking', '이거 두 개 주세요. 안 맵게 해 주세요.', 'Two of these please. Not spicy, please.', 'igeo du gae juseyo. an maepge hae juseyo.', null, null, 10),
  ('lesson-food-restaurant-summary-11', 'lesson-food-restaurant', 'summary', null, null, null, null, '{"points":["이거 + counter + 주세요 orders anything you can point at.","계산할게요 asks for the bill.","안 맵게 해 주세요 saves your evening."]}'::jsonb, 11),
  ('lesson-food-convenience-introduction-0', 'lesson-food-convenience', 'introduction', null, 'The 편의점 is a Korean institution. You only need four lines to use one perfectly.', null, null, '{"heading":"Convenience Store"}'::jsonb, 0),
  ('lesson-food-convenience-vocabulary-1', 'lesson-food-convenience', 'vocabulary', null, null, null, null, '{"vocabularyId":"v-pyeonuijeom"}'::jsonb, 1),
  ('lesson-food-convenience-vocabulary-2', 'lesson-food-convenience', 'vocabulary', null, null, null, null, '{"vocabularyId":"v-bongtu"}'::jsonb, 2),
  ('lesson-food-convenience-vocabulary-3', 'lesson-food-convenience', 'vocabulary', null, null, null, null, '{"vocabularyId":"v-yeongsujeung"}'::jsonb, 3),
  ('lesson-food-convenience-vocabulary-4', 'lesson-food-convenience', 'vocabulary', null, null, null, null, '{"vocabularyId":"v-kadeu"}'::jsonb, 4),
  ('lesson-food-convenience-expression-5', 'lesson-food-convenience', 'expression', '봉투 주세요.', 'A bag, please.', 'bongtu juseyo.', null, null, 5),
  ('lesson-food-convenience-expression-6', 'lesson-food-convenience', 'expression', '데워 주세요.', 'Please heat it up.', 'dewo juseyo.', null, null, 6),
  ('lesson-food-convenience-expression-7', 'lesson-food-convenience', 'expression', '괜찮아요.', 'No thanks, I''m fine.', 'gwaenchanayo.', null, null, 7),
  ('lesson-food-convenience-listening-8', 'lesson-food-convenience', 'listening', '봉투 필요하세요?', 'Do you need a bag?', 'bongtu piryohaseyo?', null, null, 8),
  ('lesson-food-convenience-speaking-9', 'lesson-food-convenience', 'speaking', '이거 데워 주세요.', 'Please heat this up.', 'igeo dewo juseyo.', null, null, 9),
  ('lesson-food-convenience-summary-10', 'lesson-food-convenience', 'summary', null, null, null, null, '{"points":["데워 주세요 heats your 도시락.","Bags cost money — say 괜찮아요 to decline.","Most stores have a microwave and hot water for free."]}'::jsonb, 10),
  ('lesson-transport-subway-introduction-0', 'lesson-transport-subway', 'introduction', null, 'Seoul’s subway is signposted in English, but asking a person is still faster when you are lost.', null, null, '{"heading":"Taking the Subway"}'::jsonb, 0),
  ('lesson-transport-subway-vocabulary-1', 'lesson-transport-subway', 'vocabulary', null, null, null, null, '{"vocabularyId":"v-jihacheol"}'::jsonb, 1),
  ('lesson-transport-subway-vocabulary-2', 'lesson-transport-subway', 'vocabulary', null, null, null, null, '{"vocabularyId":"v-yeok"}'::jsonb, 2),
  ('lesson-transport-subway-vocabulary-3', 'lesson-transport-subway', 'vocabulary', null, null, null, null, '{"vocabularyId":"v-hwanseung"}'::jsonb, 3),
  ('lesson-transport-subway-vocabulary-4', 'lesson-transport-subway', 'vocabulary', null, null, null, null, '{"vocabularyId":"v-chulgu"}'::jsonb, 4),
  ('lesson-transport-subway-vocabulary-5', 'lesson-transport-subway', 'vocabulary', null, null, null, null, '{"vocabularyId":"v-eodiyeyo"}'::jsonb, 5),
  ('lesson-transport-subway-expression-6', 'lesson-transport-subway', 'expression', '강남역 어떻게 가요?', 'How do I get to Gangnam Station?', 'gangnamyeok eotteoke gayo?', null, null, 6),
  ('lesson-transport-subway-expression-7', 'lesson-transport-subway', 'expression', '어디서 환승해요?', 'Where do I transfer?', 'eodiseo hwanseunghaeyo?', null, null, 7),
  ('lesson-transport-subway-expression-8', 'lesson-transport-subway', 'expression', '삼 번 출구에서 만나요.', 'Let''s meet at exit 3.', 'sam beon chulguesseo mannayo.', null, null, 8),
  ('lesson-transport-subway-listening-9', 'lesson-transport-subway', 'listening', '이번 역은 홍대입구역입니다.', 'This stop is Hongdae Ipgu Station.', 'ibeon yeogeun hongdaeipguyeogimnida.', null, null, 9),
  ('lesson-transport-subway-speaking-10', 'lesson-transport-subway', 'speaking', '홍대입구역 어떻게 가요?', 'How do I get to Hongdae Ipgu Station?', 'hongdaeipguyeok eotteoke gayo?', null, null, 10),
  ('lesson-transport-subway-summary-11', 'lesson-transport-subway', 'summary', null, null, null, null, '{"points":["~ 어떻게 가요? asks for directions anywhere.","Exits are numbered — Koreans meet at exit numbers.","환승 is the transfer station."]}'::jsonb, 11),
  ('lesson-transport-taxi-introduction-0', 'lesson-transport-taxi', 'introduction', null, 'Three lines will get you into a taxi, to your destination, and back out again.', null, null, '{"heading":"Taking a Taxi"}'::jsonb, 0),
  ('lesson-transport-taxi-vocabulary-1', 'lesson-transport-taxi', 'vocabulary', null, null, null, null, '{"vocabularyId":"v-taeksi"}'::jsonb, 1),
  ('lesson-transport-taxi-vocabulary-2', 'lesson-transport-taxi', 'vocabulary', null, null, null, null, '{"vocabularyId":"v-yeok"}'::jsonb, 2),
  ('lesson-transport-taxi-vocabulary-3', 'lesson-transport-taxi', 'vocabulary', null, null, null, null, '{"vocabularyId":"v-yeogiyo-stop"}'::jsonb, 3),
  ('lesson-transport-taxi-expression-4', 'lesson-transport-taxi', 'expression', '강남역으로 가 주세요.', 'To Gangnam Station, please.', 'gangnamyeogeuro ga juseyo.', null, null, 4),
  ('lesson-transport-taxi-expression-5', 'lesson-transport-taxi', 'expression', '여기서 세워 주세요.', 'Please stop here.', 'yeogiseo sewo juseyo.', null, null, 5),
  ('lesson-transport-taxi-expression-6', 'lesson-transport-taxi', 'expression', '카드 되나요?', 'Can I pay by card?', 'kadeu doenayo?', null, null, 6),
  ('lesson-transport-taxi-listening-7', 'lesson-transport-taxi', 'listening', '어디로 모실까요?', 'Where shall I take you?', 'eodiro mosilkkayo?', null, null, 7),
  ('lesson-transport-taxi-speaking-8', 'lesson-transport-taxi', 'speaking', '이 주소로 가 주세요.', 'Please go to this address.', 'i jusoro ga juseyo.', null, null, 8),
  ('lesson-transport-taxi-summary-9', 'lesson-transport-taxi', 'summary', null, null, null, null, '{"points":["목적지 + 으로/로 가 주세요 sets the destination.","여기서 세워 주세요 stops the car.","되나요? asks \"is that possible?\" about anything."]}'::jsonb, 9),
  ('lesson-shopping-sizes-introduction-0', 'lesson-shopping-sizes', 'introduction', null, 'Korean shops are hands-on. Ask to try things and to swap sizes without any awkwardness.', null, null, '{"heading":"Sizes & Colors"}'::jsonb, 0),
  ('lesson-shopping-sizes-vocabulary-1', 'lesson-shopping-sizes', 'vocabulary', null, null, null, null, '{"vocabularyId":"v-halin"}'::jsonb, 1),
  ('lesson-shopping-sizes-vocabulary-2', 'lesson-shopping-sizes', 'vocabulary', null, null, null, null, '{"vocabularyId":"v-eolmayeyo"}'::jsonb, 2),
  ('lesson-shopping-sizes-vocabulary-3', 'lesson-shopping-sizes', 'vocabulary', null, null, null, null, '{"vocabularyId":"v-kadeu"}'::jsonb, 3),
  ('lesson-shopping-sizes-expression-4', 'lesson-shopping-sizes', 'expression', '입어 봐도 돼요?', 'Can I try it on?', 'ibeo bwado dwaeyo?', null, null, 4),
  ('lesson-shopping-sizes-expression-5', 'lesson-shopping-sizes', 'expression', '더 큰 사이즈 있어요?', 'Do you have a bigger size?', 'deo keun saijeu isseoyo?', null, null, 5),
  ('lesson-shopping-sizes-expression-6', 'lesson-shopping-sizes', 'expression', '다른 색 있어요?', 'Do you have another colour?', 'dareun saek isseoyo?', null, null, 6),
  ('lesson-shopping-sizes-listening-7', 'lesson-shopping-sizes', 'listening', '이거 새 상품이에요.', 'This one is brand new.', 'igeo sae sangpumieyo.', null, null, 7),
  ('lesson-shopping-sizes-speaking-8', 'lesson-shopping-sizes', 'speaking', '더 큰 사이즈 있어요?', 'Do you have a bigger size?', 'deo keun saijeu isseoyo?', null, null, 8),
  ('lesson-shopping-sizes-summary-9', 'lesson-shopping-sizes', 'summary', null, null, null, null, '{"points":["~ 있어요? asks if a shop has something.","~해도 돼요? asks permission.","더 + adjective = \"more ~\"."]}'::jsonb, 9),
  ('lesson-conversation-smalltalk-introduction-0', 'lesson-conversation-smalltalk', 'introduction', null, 'Korean small talk runs on food, weather and weekends. Three questions keep any conversation alive.', null, null, '{"heading":"Small Talk"}'::jsonb, 0),
  ('lesson-conversation-smalltalk-vocabulary-1', 'lesson-conversation-smalltalk', 'vocabulary', null, null, null, null, '{"vocabularyId":"v-oneul"}'::jsonb, 1),
  ('lesson-conversation-smalltalk-vocabulary-2', 'lesson-conversation-smalltalk', 'vocabulary', null, null, null, null, '{"vocabularyId":"v-bap"}'::jsonb, 2),
  ('lesson-conversation-smalltalk-vocabulary-3', 'lesson-conversation-smalltalk', 'vocabulary', null, null, null, null, '{"vocabularyId":"v-jaemiisseoyo"}'::jsonb, 3),
  ('lesson-conversation-smalltalk-vocabulary-4', 'lesson-conversation-smalltalk', 'vocabulary', null, null, null, null, '{"vocabularyId":"v-bappayo"}'::jsonb, 4),
  ('lesson-conversation-smalltalk-expression-5', 'lesson-conversation-smalltalk', 'expression', '밥 먹었어요?', 'Have you eaten?', 'bap meogeosseoyo?', null, '{"note":"This is a greeting, not a dinner invitation."}'::jsonb, 5),
  ('lesson-conversation-smalltalk-expression-6', 'lesson-conversation-smalltalk', 'expression', '주말에 뭐 했어요?', 'What did you do on the weekend?', 'jumare mwo haesseoyo?', null, null, 6),
  ('lesson-conversation-smalltalk-expression-7', 'lesson-conversation-smalltalk', 'expression', '요즘 어때요?', 'How have you been lately?', 'yojeum eottaeyo?', null, null, 7),
  ('lesson-conversation-smalltalk-listening-8', 'lesson-conversation-smalltalk', 'listening', '요즘 너무 바빠요.', 'I''m so busy lately.', 'yojeum neomu bappayo.', null, null, 8),
  ('lesson-conversation-smalltalk-speaking-9', 'lesson-conversation-smalltalk', 'speaking', '주말에 뭐 했어요?', 'What did you do on the weekend?', 'jumare mwo haesseoyo?', null, null, 9),
  ('lesson-conversation-smalltalk-summary-10', 'lesson-conversation-smalltalk', 'summary', null, null, null, null, '{"points":["밥 먹었어요? means \"how are you\".","뭐 했어요? asks what someone did.","어때요? asks for an opinion about anything."]}'::jsonb, 10),
  ('lesson-living-delivery-introduction-0', 'lesson-living-delivery', 'introduction', null, 'Korean delivery is fast and phone-based. These lines handle the driver, the app and the front desk.', null, null, '{"heading":"Package Delivery"}'::jsonb, 0),
  ('lesson-living-delivery-vocabulary-1', 'lesson-living-delivery', 'vocabulary', null, null, null, null, '{"vocabularyId":"v-baedal"}'::jsonb, 1),
  ('lesson-living-delivery-vocabulary-2', 'lesson-living-delivery', 'vocabulary', null, null, null, null, '{"vocabularyId":"v-pojang"}'::jsonb, 2),
  ('lesson-living-delivery-vocabulary-3', 'lesson-living-delivery', 'vocabulary', null, null, null, null, '{"vocabularyId":"v-gwaenchanayo"}'::jsonb, 3),
  ('lesson-living-delivery-expression-4', 'lesson-living-delivery', 'expression', '문 앞에 놓아 주세요.', 'Please leave it at the door.', 'mun ape noa juseyo.', null, null, 4),
  ('lesson-living-delivery-expression-5', 'lesson-living-delivery', 'expression', '택배 왔어요?', 'Did the package arrive?', 'taekbae wasseoyo?', null, null, 5),
  ('lesson-living-delivery-expression-6', 'lesson-living-delivery', 'expression', '경비실에 맡겨 주세요.', 'Please leave it with the security desk.', 'gyeongbisire matgyeo juseyo.', null, null, 6),
  ('lesson-living-delivery-listening-7', 'lesson-living-delivery', 'listening', '택배입니다. 문 앞에 뒀어요.', 'Delivery. I left it at the door.', 'taekbaeimnida. mun ape dwosseoyo.', null, null, 7),
  ('lesson-living-delivery-speaking-8', 'lesson-living-delivery', 'speaking', '문 앞에 놓아 주세요.', 'Please leave it at the door.', 'mun ape noa juseyo.', null, null, 8),
  ('lesson-living-delivery-summary-9', 'lesson-living-delivery', 'summary', null, null, null, null, '{"points":["문 앞 = in front of the door.","경비실 is the building security office.","~아/어 주세요 politely asks for a favour."]}'::jsonb, 9),
  ('lesson-travel-airport-introduction-0', 'lesson-travel-airport', 'introduction', null, 'From immigration to the airport bus, this is the Korean you need in your first hour in the country.', null, null, '{"heading":"At the Airport"}'::jsonb, 0),
  ('lesson-travel-airport-vocabulary-1', 'lesson-travel-airport', 'vocabulary', null, null, null, null, '{"vocabularyId":"v-beoseu"}'::jsonb, 1),
  ('lesson-travel-airport-vocabulary-2', 'lesson-travel-airport', 'vocabulary', null, null, null, null, '{"vocabularyId":"v-eodiyeyo"}'::jsonb, 2),
  ('lesson-travel-airport-vocabulary-3', 'lesson-travel-airport', 'vocabulary', null, null, null, null, '{"vocabularyId":"v-kadeu"}'::jsonb, 3),
  ('lesson-travel-airport-expression-4', 'lesson-travel-airport', 'expression', '여행으로 왔어요.', 'I''m here for travel.', 'yeohaengeuro wasseoyo.', null, null, 4),
  ('lesson-travel-airport-expression-5', 'lesson-travel-airport', 'expression', '티머니 카드 주세요.', 'A T-money card, please.', 'timeoni kadeu juseyo.', null, null, 5),
  ('lesson-travel-airport-expression-6', 'lesson-travel-airport', 'expression', '공항버스 어디서 타요?', 'Where do I catch the airport bus?', 'gonghangbeoseu eodiseo tayo?', null, null, 6),
  ('lesson-travel-airport-listening-7', 'lesson-travel-airport', 'listening', '방문 목적이 뭐예요?', 'What is the purpose of your visit?', 'bangmun mokjeogi mwoyeyo?', null, null, 7),
  ('lesson-travel-airport-speaking-8', 'lesson-travel-airport', 'speaking', '공항버스 어디서 타요?', 'Where do I catch the airport bus?', 'gonghangbeoseu eodiseo tayo?', null, null, 8),
  ('lesson-travel-airport-summary-9', 'lesson-travel-airport', 'summary', null, null, null, null, '{"points":["~으로 왔어요 states your purpose.","어디서 타요? asks where to board.","T-money works on every bus, subway and most taxis."]}'::jsonb, 9),
  ('lesson-work-greetings-introduction-0', 'lesson-work-greetings', 'introduction', null, 'Korean offices run on a handful of set phrases. Using them correctly signals that you understand the culture.', null, null, '{"heading":"Office Greetings"}'::jsonb, 0),
  ('lesson-work-greetings-vocabulary-1', 'lesson-work-greetings', 'vocabulary', null, null, null, null, '{"vocabularyId":"v-hoesa"}'::jsonb, 1),
  ('lesson-work-greetings-vocabulary-2', 'lesson-work-greetings', 'vocabulary', null, null, null, null, '{"vocabularyId":"v-sugohasyeotseumnida"}'::jsonb, 2),
  ('lesson-work-greetings-vocabulary-3', 'lesson-work-greetings', 'vocabulary', null, null, null, null, '{"vocabularyId":"v-hoeui"}'::jsonb, 3),
  ('lesson-work-greetings-expression-4', 'lesson-work-greetings', 'expression', '안녕하십니까.', 'Good morning (formal).', 'annyeonghasimnikka.', null, null, 4),
  ('lesson-work-greetings-expression-5', 'lesson-work-greetings', 'expression', '수고하셨습니다.', 'Good work today.', 'sugohasyeotseumnida.', null, '{"note":"Say it to peers and juniors, not to your boss."}'::jsonb, 5),
  ('lesson-work-greetings-expression-6', 'lesson-work-greetings', 'expression', '먼저 들어가 보겠습니다.', 'I''ll head out first.', 'meonjeo deureoga bogesseumnida.', null, null, 6),
  ('lesson-work-greetings-listening-7', 'lesson-work-greetings', 'listening', '회의 세 시에 시작합니다.', 'The meeting starts at 3.', 'hoeui se sie sijakhamnida.', null, null, 7),
  ('lesson-work-greetings-speaking-8', 'lesson-work-greetings', 'speaking', '수고하셨습니다. 먼저 들어가 보겠습니다.', 'Good work today. I''ll head out first.', 'sugohasyeotseumnida. meonjeo deureoga bogesseumnida.', null, null, 8),
  ('lesson-work-greetings-summary-9', 'lesson-work-greetings', 'summary', null, null, null, null, '{"points":["~습니다 is the formal business ending.","수고하셨습니다 closes the workday.","Leaving before others needs a polite phrase."]}'::jsonb, 9)
on conflict (id) do update set lesson_id = excluded.lesson_id, content_type = excluded.content_type, korean_text = excluded.korean_text, english_text = excluded.english_text, romanization = excluded.romanization, audio_url = excluded.audio_url, metadata = excluded.metadata, order_index = excluded.order_index;

insert into public.quizzes (id, lesson_id, question_type, question, prompt, correct_answer, options, metadata)
values
  ('q-hello-1', 'lesson-greetings-hello', 'multiple_choice_ko_en', 'What does 안녕하세요 mean?', '안녕하세요', 'Hello', ARRAY['Hello', 'Thank you', 'Goodbye', 'Sorry']::text[], null),
  ('q-hello-2', 'lesson-greetings-hello', 'multiple_choice_en_ko', 'How do you say goodbye to someone who is leaving?', null, '안녕히 가세요', ARRAY['안녕히 가세요', '안녕히 계세요', '감사합니다', '반가워요']::text[], null),
  ('q-hello-3', 'lesson-greetings-hello', 'true_false', '안녕하세요 can be used in the morning and the evening.', null, 'True', ARRAY['True', 'False']::text[], null),
  ('q-hello-4', 'lesson-greetings-hello', 'sentence_ordering', 'Put the sentence in the right order.', 'Nice to meet you.', '만나서 반가워요', ARRAY['만나서', '반가워요']::text[], null),
  ('q-yesno-1', 'lesson-greetings-yesno', 'multiple_choice_ko_en', 'What does 아니요 mean?', '아니요', 'No', ARRAY['No', 'Yes', 'Maybe', 'Please']::text[], null),
  ('q-yesno-2', 'lesson-greetings-yesno', 'fill_in_the_blank', 'Complete: ___, 괜찮아요. ("No, I''m fine.")', '___, 괜찮아요.', '아니요', ARRAY['아니요', '네', '주세요', '감사']::text[], null),
  ('q-thanks-1', 'lesson-greetings-thanks', 'multiple_choice_en_ko', 'How do you say "thank you" formally?', null, '감사합니다', ARRAY['감사합니다', '죄송합니다', '천만에요', '괜찮아요']::text[], null),
  ('q-thanks-2', 'lesson-greetings-thanks', 'multiple_choice_ko_en', 'What does 죄송합니다 mean?', '죄송합니다', 'I am sorry', ARRAY['I am sorry', 'Thank you', 'You are welcome', 'Excuse me']::text[], null),
  ('q-thanks-3', 'lesson-greetings-thanks', 'word_matching', 'Match the Korean to its meaning.', null, '천만에요', ARRAY['천만에요', '감사합니다', '죄송합니다', '반가워요']::text[], '{"matchTarget":"You''re welcome"}'::jsonb),
  ('q-intro-1', 'lesson-greetings-intro', 'multiple_choice_ko_en', 'What does 저는 미국에서 왔어요 mean?', '저는 미국에서 왔어요.', 'I came from the United States', ARRAY['I came from the United States', 'I am going to America', 'I live in Korea', 'I like America']::text[], null),
  ('q-intro-2', 'lesson-greetings-intro', 'fill_in_the_blank', 'Complete: 이름이 ___? ("What is your name?")', '이름이 ___?', '뭐예요', ARRAY['뭐예요', '주세요', '왔어요', '괜찮아요']::text[], null),
  ('q-intro-3', 'lesson-greetings-intro', 'sentence_ordering', 'Build: "I am Alex."', 'I am Alex.', '저는 알렉스예요', ARRAY['저는', '알렉스예요']::text[], null),
  ('q-coffee-1', 'lesson-cafe-coffee', 'multiple_choice_en_ko', 'How do you order one americano?', null, '아메리카노 한 잔 주세요', ARRAY['아메리카노 한 잔 주세요', '아메리카노 얼마예요?', '물 좀 주세요', '카드로 할게요']::text[], null),
  ('q-coffee-2', 'lesson-cafe-coffee', 'multiple_choice_ko_en', 'What does 주세요 mean?', '주세요', 'Please give me', ARRAY['Please give me', 'Thank you', 'How much', 'I am sorry']::text[], null),
  ('q-coffee-3', 'lesson-cafe-coffee', 'listening', 'What did you hear?', '아이스 아메리카노 주세요.', 'An iced americano, please', ARRAY['An iced americano, please', 'A hot latte, please', 'Water, please', 'The receipt, please']::text[], null),
  ('q-coffee-4', 'lesson-cafe-coffee', 'sentence_ordering', 'Build: "One americano, please."', 'One americano, please.', '아메리카노 한 잔 주세요', ARRAY['아메리카노', '한 잔', '주세요']::text[], null),
  ('q-coffee-5', 'lesson-cafe-coffee', 'true_false', '테이크아웃 means you will drink it in the cafe.', null, 'False', ARRAY['True', 'False']::text[], null),
  ('q-water-1', 'lesson-cafe-water', 'multiple_choice_ko_en', 'What does 저기요 mean?', '저기요', 'Excuse me', ARRAY['Excuse me', 'Over there', 'Goodbye', 'Please wait']::text[], null),
  ('q-water-2', 'lesson-cafe-water', 'fill_in_the_blank', 'Complete: 물 좀 ___. ("Some water, please.")', '물 좀 ___.', '주세요', ARRAY['주세요', '왔어요', '괜찮아요', '얼마예요']::text[], null),
  ('q-paying-1', 'lesson-cafe-paying', 'multiple_choice_ko_en', 'What does 얼마예요? mean?', '얼마예요?', 'How much is it?', ARRAY['How much is it?', 'Where is it?', 'What is it?', 'Who is it?']::text[], null),
  ('q-paying-2', 'lesson-cafe-paying', 'multiple_choice_en_ko', 'How do you ask for a receipt?', null, '영수증 주세요', ARRAY['영수증 주세요', '봉투 주세요', '카드 되나요?', '얼마예요?']::text[], null),
  ('q-paying-3', 'lesson-cafe-paying', 'word_matching', 'Match the Korean to its meaning.', null, '현금', ARRAY['현금', '카드', '영수증', '봉투']::text[], '{"matchTarget":"Cash"}'::jsonb),
  ('q-hangul-1', 'lesson-hangul-consonants', 'multiple_choice_ko_en', 'How is ㄱ pronounced?', 'ㄱ', 'g / k', ARRAY['g / k', 'n', 'm', 's']::text[], null),
  ('q-hangul-2', 'lesson-hangul-consonants', 'multiple_choice_ko_en', 'How do you read 가?', '가', 'ga', ARRAY['ga', 'na', 'ma', 'sa']::text[], null),
  ('q-hangul-3', 'lesson-hangul-vowels', 'multiple_choice_ko_en', 'How is ㅗ pronounced?', 'ㅗ', 'o', ARRAY['o', 'a', 'u', 'eo']::text[], null),
  ('q-hangul-4', 'lesson-hangul-vowels', 'true_false', 'Horizontal vowels like ㅗ are written under the consonant.', null, 'True', ARRAY['True', 'False']::text[], null),
  ('q-numbers-1', 'lesson-numbers-sino', 'multiple_choice_ko_en', 'What number is 오?', '오', '5', ARRAY['5', '3', '7', '10']::text[], null),
  ('q-numbers-2', 'lesson-numbers-native', 'fill_in_the_blank', 'Complete: 커피 ___ 잔 주세요. ("Two coffees, please.")', '커피 ___ 잔 주세요.', '두', ARRAY['두', '이', '둘', '다섯']::text[], null),
  ('q-restaurant-1', 'lesson-food-restaurant', 'multiple_choice_ko_en', 'What does 주문하시겠어요? mean?', '주문하시겠어요?', 'Would you like to order?', ARRAY['Would you like to order?', 'Is it spicy?', 'How many people?', 'Do you need a bag?']::text[], null),
  ('q-restaurant-2', 'lesson-food-restaurant', 'multiple_choice_en_ko', 'How do you ask for the bill?', null, '계산할게요', ARRAY['계산할게요', '주문할게요', '데워 주세요', '포장해 주세요']::text[], null),
  ('q-convenience-1', 'lesson-food-convenience', 'multiple_choice_ko_en', 'What does 데워 주세요 mean?', '데워 주세요', 'Please heat it up', ARRAY['Please heat it up', 'Please pack it', 'Please give me a bag', 'Please stop here']::text[], null),
  ('q-subway-1', 'lesson-transport-subway', 'multiple_choice_ko_en', 'What does 환승 mean?', '환승', 'Transfer', ARRAY['Transfer', 'Exit', 'Station', 'Ticket']::text[], null),
  ('q-subway-2', 'lesson-transport-subway', 'sentence_ordering', 'Build: "How do I get to Gangnam Station?"', 'How do I get to Gangnam Station?', '강남역 어떻게 가요', ARRAY['강남역', '어떻게', '가요']::text[], null)
on conflict (id) do update set lesson_id = excluded.lesson_id, question_type = excluded.question_type, question = excluded.question, prompt = excluded.prompt, correct_answer = excluded.correct_answer, options = excluded.options, metadata = excluded.metadata;

insert into public.daily_phrases (id, korean, english, romanization, category, audio_url, publish_date)
values
  ('dp-01', '오늘 뭐 해요?', 'What are you doing today?', 'oneul mwo haeyo?', 'friends', null, '2025-01-01'),
  ('dp-02', '아메리카노 한 잔 주세요.', 'One americano, please.', 'amerikano han jan juseyo.', 'food', null, '2025-01-02'),
  ('dp-03', '진짜 대박이에요!', 'That''s awesome!', 'jinjja daebagieyo!', 'slang', null, '2025-01-03'),
  ('dp-04', '밥 먹었어요?', 'Have you eaten?', 'bap meogeosseoyo?', 'culture', null, '2025-01-04'),
  ('dp-05', '천천히 말해 주세요.', 'Please speak slowly.', 'cheoncheonhi malhae juseyo.', 'travel', null, '2025-01-05'),
  ('dp-06', '우리 언제 만날까요?', 'When should we meet?', 'uri eonje mannalkkayo?', 'dating', null, '2025-01-06'),
  ('dp-07', '수고하셨습니다.', 'Good work today.', 'sugohasyeotseumnida.', 'work', null, '2025-01-07'),
  ('dp-08', '이거 진짜 맛있어요.', 'This is really delicious.', 'igeo jinjja masisseoyo.', 'food', null, '2025-01-08'),
  ('dp-09', '화장실이 어디예요?', 'Where is the bathroom?', 'hwajangsiri eodiyeyo?', 'travel', null, '2025-01-09'),
  ('dp-10', '오늘 시간 있어요?', 'Do you have time today?', 'oneul sigan isseoyo?', 'dating', null, '2025-01-10'),
  ('dp-11', '완전 좋아요!', 'I totally love it!', 'wanjeon joayo!', 'slang', null, '2025-01-11'),
  ('dp-12', '조심히 가세요.', 'Get home safely.', 'josimhi gaseyo.', 'culture', null, '2025-01-12'),
  ('dp-13', '내일 회의 있어요.', 'There is a meeting tomorrow.', 'naeil hoeui isseoyo.', 'work', null, '2025-01-13'),
  ('dp-14', '같이 갈래요?', 'Do you want to go together?', 'gachi gallaeyo?', 'friends', null, '2025-01-14'),
  ('dp-15', '여기서 세워 주세요.', 'Please stop here.', 'yeogiseo sewo juseyo.', 'travel', null, '2025-01-15'),
  ('dp-16', '커피 한잔할래요?', 'Want to grab a coffee?', 'keopi hanjanhallaeyo?', 'dating', null, '2025-01-16'),
  ('dp-17', '진짜요?', 'Really?', 'jinjjayo?', 'friends', null, '2025-01-17'),
  ('dp-18', '배고파 죽겠어요.', 'I''m starving.', 'baegopa jukgesseoyo.', 'slang', null, '2025-01-18')
on conflict (id) do update set korean = excluded.korean, english = excluded.english, romanization = excluded.romanization, category = excluded.category, audio_url = excluded.audio_url, publish_date = excluded.publish_date;
