#!/usr/bin/env bash
# Concatenates the migrations into one paste-able file for the Supabase SQL
# Editor. Four ordered copy-pastes is four chances to run them out of order.
set -euo pipefail
cd "$(dirname "$0")/.."

{
  cat <<'HEADER'
-- =============================================================================
-- KoreanGo — complete schema, all migrations in order.
--
-- Generated by scripts/build-schema.sh from supabase/migrations/. Do not edit
-- this file; edit a migration and regenerate, or the two drift apart.
--
-- Paste the whole thing into the Supabase SQL Editor and run it ONCE, on a
-- fresh project.
--
-- It is deliberately not re-runnable: these are migrations, so the tables,
-- indexes, triggers and 28 policies are plain `create` statements and a second
-- run fails on the first object that already exists. If a run half-succeeds,
-- reset the database (Project Settings -> General -> Reset database) and run
-- it again from clean rather than picking through the errors.
-- =============================================================================

HEADER

  for file in supabase/migrations/*.sql; do
    printf '\n\n-- ###########################################################################\n'
    printf -- '-- %s\n' "$(basename "$file")"
    printf -- '-- ###########################################################################\n\n'
    cat "$file"
  done
} > supabase/schema.sql

echo "supabase/schema.sql written ($(wc -l < supabase/schema.sql) lines)"
